# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 17:40
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0008_auto_20151119_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aarelation',
            name='administrator_notes',
            field=models.TextField(blank=True, help_text=b'Curatorial discussion about the record.', null=True),
        ),
        migrations.AlterField(
            model_name='aarelation',
            name='created_by_fm',
            field=models.CharField(blank=True, help_text=b'Value of CreatedBy from the original FM database.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aarelation',
            name='created_on_fm',
            field=models.DateTimeField(help_text=b'Value of CreatedOn from the original FM database.', null=True),
        ),
        migrations.AlterField(
            model_name='aarelation',
            name='id',
            field=models.CharField(help_text=b'In the format {PRE}{ZEROS}{NN}, where PRE is a three-letter prefix indicating the record type (e.g. CBA for Authority), NN is an integer, and ZEROS is 0-9 zeros to pad NN such that ZEROS+NN is nine characters in length.', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aarelation',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text=b'The most recent user to modify this object.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aarelation',
            name='modified_by_fm',
            field=models.CharField(blank=True, help_text=b'Value of ModifiedOn from the original FM database.', max_length=255, verbose_name=b'modified by (FM)'),
        ),
        migrations.AlterField(
            model_name='aarelation',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, help_text=b'Date and time at which this object was last updated.', null=True),
        ),
        migrations.AlterField(
            model_name='aarelation',
            name='modified_on_fm',
            field=models.DateTimeField(help_text=b'Value of ModifiedBy from the original FM database.', null=True, verbose_name=b'modified on (FM)'),
        ),
        migrations.AlterField(
            model_name='aarelation',
            name='public',
            field=models.BooleanField(default=True, help_text=b'Controls whether this instance can be viewed by end users.'),
        ),
        migrations.AlterField(
            model_name='aarelation',
            name='record_history',
            field=models.TextField(blank=True, help_text=b"Notes about the provenance of the information in this record. e.g. 'supplied by the author,' 'imported from SHOT bibliography,' 'generated by crawling UC Press website'", null=True),
        ),
        migrations.AlterField(
            model_name='aarelation',
            name='type_controlled',
            field=models.CharField(blank=True, choices=[(b'IDTO', b'Is Identical To'), (b'PAOF', b'Is Parent Of'), (b'PRETO', b'Happened Previous To'), (b'OFOF', b'Is Officer Of'), (b'ASWI', b'Is Associated With')], help_text=b'Controlled term specifying the nature of the relationship (the predicate between the subject and object).', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='aarelation',
            name='type_free',
            field=models.CharField(blank=True, help_text=b'Free text description of the relationship.', max_length=255),
        ),
        migrations.AlterField(
            model_name='acrelation',
            name='administrator_notes',
            field=models.TextField(blank=True, help_text=b'Curatorial discussion about the record.', null=True),
        ),
        migrations.AlterField(
            model_name='acrelation',
            name='confidence_measure',
            field=models.FloatField(default=1.0, help_text=b'Currently not used: will be used to assess the confidence of the link in the event that there is some ambiguity.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='acrelation',
            name='created_by_fm',
            field=models.CharField(blank=True, help_text=b'Value of CreatedBy from the original FM database.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='acrelation',
            name='created_on_fm',
            field=models.DateTimeField(help_text=b'Value of CreatedOn from the original FM database.', null=True),
        ),
        migrations.AlterField(
            model_name='acrelation',
            name='data_display_order',
            field=models.FloatField(default=1.0, help_text=b'Position at which the authority should be displayed in the citation detail view. Whole numbers or decimals can be used.'),
        ),
        migrations.AlterField(
            model_name='acrelation',
            name='id',
            field=models.CharField(help_text=b'In the format {PRE}{ZEROS}{NN}, where PRE is a three-letter prefix indicating the record type (e.g. CBA for Authority), NN is an integer, and ZEROS is 0-9 zeros to pad NN such that ZEROS+NN is nine characters in length.', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='acrelation',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text=b'The most recent user to modify this object.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='acrelation',
            name='modified_by_fm',
            field=models.CharField(blank=True, help_text=b'Value of ModifiedOn from the original FM database.', max_length=255, verbose_name=b'modified by (FM)'),
        ),
        migrations.AlterField(
            model_name='acrelation',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, help_text=b'Date and time at which this object was last updated.', null=True),
        ),
        migrations.AlterField(
            model_name='acrelation',
            name='modified_on_fm',
            field=models.DateTimeField(help_text=b'Value of ModifiedBy from the original FM database.', null=True, verbose_name=b'modified on (FM)'),
        ),
        migrations.AlterField(
            model_name='acrelation',
            name='name_as_entered',
            field=models.CharField(blank=True, help_text=b'Display for the authority as it is has been used in a publication.', max_length=255),
        ),
        migrations.AlterField(
            model_name='acrelation',
            name='name_for_display_in_citation',
            field=models.CharField(help_text=b"Display for the authority as it is to be used when being displayed with the citation. Eg. the form of the author's name as it appears on a publication--say, J.E. Koval--which might be different from the name of the authority--Jenifer Elizabeth Koval.", max_length=255),
        ),
        migrations.AlterField(
            model_name='acrelation',
            name='public',
            field=models.BooleanField(default=True, help_text=b'Controls whether this instance can be viewed by end users.'),
        ),
        migrations.AlterField(
            model_name='acrelation',
            name='record_history',
            field=models.TextField(blank=True, help_text=b"Notes about the provenance of the information in this record. e.g. 'supplied by the author,' 'imported from SHOT bibliography,' 'generated by crawling UC Press website'", null=True),
        ),
        migrations.AlterField(
            model_name='acrelation',
            name='relationship_weight',
            field=models.FloatField(default=1.0, help_text=b'Currently not used: helps to assess how significant this relationship is--to be used mostly in marking subjects.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='acrelation',
            name='type_broad_controlled',
            field=models.CharField(blank=True, choices=[(b'PR', b'Has Personal Responsibility For'), (b'SC', b'Provides Subject Content About'), (b'IH', b'Is Institutional Host Of'), (b'PH', b'Is Publication Host Of')], help_text=b'Used to specify the nature of the relationship between authority (as the subject) and the citation (as the object) more broadly than the relationship type.', max_length=2, verbose_name=b'relationship type (broad)'),
        ),
        migrations.AlterField(
            model_name='acrelation',
            name='type_controlled',
            field=models.CharField(blank=True, choices=[(b'AU', b'Author'), (b'ED', b'Editor'), (b'AD', b'Advisor'), (b'CO', b'Contributor'), (b'TR', b'Translator'), (b'SU', b'Subject'), (b'CA', b'Category'), (b'PU', b'Publisher'), (b'SC', b'School'), (b'IN', b'Institution'), (b'ME', b'Meeting'), (b'PE', b'Periodical'), (b'BS', b'Book Series')], help_text=b'Used to specify the nature of the relationship between authority (as the subject) and the citation (as the object).', max_length=2, null=True, verbose_name=b'relationship type'),
        ),
        migrations.AlterField(
            model_name='acrelation',
            name='type_free',
            field=models.CharField(blank=True, help_text=b"\n    Free-text description of the role that the authority plays in the\n    citation (e.g. 'introduction by', 'dissertation supervisor', etc).\n    ", max_length=255, verbose_name=b'relationship type (free-text)'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='child_class',
            field=models.CharField(blank=True, help_text=b'Name of the child model for this instance.', max_length=255),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='subject_field',
            field=models.CharField(blank=True, help_text=b'The name of the field in ``subject`` to which this annotation refers. For example, ``title``.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='administrator_notes',
            field=models.TextField(blank=True, help_text=b'Curatorial discussion about the record.', null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='created_by_fm',
            field=models.CharField(blank=True, help_text=b'Value of CreatedBy from the original FM database.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='created_on_fm',
            field=models.DateTimeField(help_text=b'Value of CreatedOn from the original FM database.', null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='description',
            field=models.TextField(blank=True, help_text=b'Additional information about this attribute.'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='id',
            field=models.CharField(help_text=b'In the format {PRE}{ZEROS}{NN}, where PRE is a three-letter prefix indicating the record type (e.g. CBA for Authority), NN is an integer, and ZEROS is 0-9 zeros to pad NN such that ZEROS+NN is nine characters in length.', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text=b'The most recent user to modify this object.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='modified_by_fm',
            field=models.CharField(blank=True, help_text=b'Value of ModifiedOn from the original FM database.', max_length=255, verbose_name=b'modified by (FM)'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, help_text=b'Date and time at which this object was last updated.', null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='modified_on_fm',
            field=models.DateTimeField(help_text=b'Value of ModifiedBy from the original FM database.', null=True, verbose_name=b'modified on (FM)'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='public',
            field=models.BooleanField(default=True, help_text=b'Controls whether this instance can be viewed by end users.'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='record_history',
            field=models.TextField(blank=True, help_text=b"Notes about the provenance of the information in this record. e.g. 'supplied by the author,' 'imported from SHOT bibliography,' 'generated by crawling UC Press website'", null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='type_controlled',
            field=models.ForeignKey(help_text=b'The "type" field determines what kinds of values are acceptable for this attribute.', on_delete=django.db.models.deletion.CASCADE, to='isisdata.AttributeType', verbose_name=b'type'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='value_freeform',
            field=models.CharField(blank=True, help_text=b'Non-normalized value, e.g. an approximate date, or a date range.', max_length=255, verbose_name=b'freeform value'),
        ),
        migrations.AlterField(
            model_name='attributetype',
            name='display_name',
            field=models.CharField(blank=True, help_text=b'The "name" attribute is not always suitable for display in public views. This field provides the name to be displayed to users.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='authority',
            name='administrator_notes',
            field=models.TextField(blank=True, help_text=b'Curatorial discussion about the record.', null=True),
        ),
        migrations.AlterField(
            model_name='authority',
            name='classification_code',
            field=models.CharField(blank=True, help_text=b'alphanumeric code used in previous classification systems to describe classification terms. Primarily of historical interest only. Used primarily for Codes for the classificationTerms. however, can be used for other kinds of terms as appropriate.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='authority',
            name='classification_hierarchy',
            field=models.CharField(blank=True, help_text=b'Used for Classification Terms to describe where they fall in the hierarchy.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='authority',
            name='classification_system',
            field=models.CharField(blank=True, choices=[(b'SWP', b'SWP'), (b'NEU', b'Neu'), (b'MW', b'MW'), (b'SHOT', b'SHOT'), (b'SAC', b'SAC')], help_text=b'Specifies the classification system that is the source of the authority. Used to group resources by the Classification system. The system used currently is the Weldon System. All the other ones are for reference or archival purposes only.', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='authority',
            name='created_by_fm',
            field=models.CharField(blank=True, help_text=b'Value of CreatedBy from the original FM database.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='authority',
            name='created_on_fm',
            field=models.DateTimeField(help_text=b'Value of CreatedOn from the original FM database.', null=True),
        ),
        migrations.AlterField(
            model_name='authority',
            name='description',
            field=models.TextField(blank=True, help_text=b"A brief description that will be displayed to help identify the authority. Such as, brief bio or a scope note. For classification terms will be text like 'Classification term from the XXX classification schema.'", null=True),
        ),
        migrations.AlterField(
            model_name='authority',
            name='id',
            field=models.CharField(help_text=b'In the format {PRE}{ZEROS}{NN}, where PRE is a three-letter prefix indicating the record type (e.g. CBA for Authority), NN is an integer, and ZEROS is 0-9 zeros to pad NN such that ZEROS+NN is nine characters in length.', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='authority',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text=b'The most recent user to modify this object.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='authority',
            name='modified_by_fm',
            field=models.CharField(blank=True, help_text=b'Value of ModifiedOn from the original FM database.', max_length=255, verbose_name=b'modified by (FM)'),
        ),
        migrations.AlterField(
            model_name='authority',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, help_text=b'Date and time at which this object was last updated.', null=True),
        ),
        migrations.AlterField(
            model_name='authority',
            name='modified_on_fm',
            field=models.DateTimeField(help_text=b'Value of ModifiedBy from the original FM database.', null=True, verbose_name=b'modified on (FM)'),
        ),
        migrations.AlterField(
            model_name='authority',
            name='name',
            field=models.CharField(help_text=b'Name, title, or other main term for the authority as will be displayed.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='authority',
            name='public',
            field=models.BooleanField(default=True, help_text=b'Controls whether this instance can be viewed by end users.'),
        ),
        migrations.AlterField(
            model_name='authority',
            name='record_history',
            field=models.TextField(blank=True, help_text=b"Notes about the provenance of the information in this record. e.g. 'supplied by the author,' 'imported from SHOT bibliography,' 'generated by crawling UC Press website'", null=True),
        ),
        migrations.AlterField(
            model_name='authority',
            name='type_controlled',
            field=models.CharField(blank=True, choices=[(b'PE', b'Person'), (b'IN', b'Institution'), (b'TI', b'Time Period'), (b'GE', b'Geographic Term'), (b'SE', b'Serial Publication'), (b'CT', b'Classification Term'), (b'CO', b'Concept'), (b'CW', b'Creative Work'), (b'EV', b'Event'), (b'CR', b'Cross-reference'), (b'PU', b'Publisher')], help_text=b'Specifies authority type. Each authority thema has its own list of controlled type vocabulary.', max_length=2, null=True, verbose_name=b'type'),
        ),
        migrations.AlterField(
            model_name='ccrelation',
            name='administrator_notes',
            field=models.TextField(blank=True, help_text=b'Curatorial discussion about the record.', null=True),
        ),
        migrations.AlterField(
            model_name='ccrelation',
            name='created_by_fm',
            field=models.CharField(blank=True, help_text=b'Value of CreatedBy from the original FM database.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ccrelation',
            name='created_on_fm',
            field=models.DateTimeField(help_text=b'Value of CreatedOn from the original FM database.', null=True),
        ),
        migrations.AlterField(
            model_name='ccrelation',
            name='id',
            field=models.CharField(help_text=b'In the format {PRE}{ZEROS}{NN}, where PRE is a three-letter prefix indicating the record type (e.g. CBA for Authority), NN is an integer, and ZEROS is 0-9 zeros to pad NN such that ZEROS+NN is nine characters in length.', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ccrelation',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text=b'The most recent user to modify this object.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ccrelation',
            name='modified_by_fm',
            field=models.CharField(blank=True, help_text=b'Value of ModifiedOn from the original FM database.', max_length=255, verbose_name=b'modified by (FM)'),
        ),
        migrations.AlterField(
            model_name='ccrelation',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, help_text=b'Date and time at which this object was last updated.', null=True),
        ),
        migrations.AlterField(
            model_name='ccrelation',
            name='modified_on_fm',
            field=models.DateTimeField(help_text=b'Value of ModifiedBy from the original FM database.', null=True, verbose_name=b'modified on (FM)'),
        ),
        migrations.AlterField(
            model_name='ccrelation',
            name='public',
            field=models.BooleanField(default=True, help_text=b'Controls whether this instance can be viewed by end users.'),
        ),
        migrations.AlterField(
            model_name='ccrelation',
            name='record_history',
            field=models.TextField(blank=True, help_text=b"Notes about the provenance of the information in this record. e.g. 'supplied by the author,' 'imported from SHOT bibliography,' 'generated by crawling UC Press website'", null=True),
        ),
        migrations.AlterField(
            model_name='ccrelation',
            name='type_controlled',
            field=models.CharField(blank=True, choices=[(b'IC', b'Includes Chapter'), (b'ISA', b'Includes Series Article'), (b'RO', b'Is Review Of'), (b'RE', b'Responds To'), (b'AS', b'Is Associated With'), (b'RB', b'Is Reviewed By')], help_text=b'Type of relationship between two citation records.', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='ccrelation',
            name='type_free',
            field=models.CharField(blank=True, help_text=b'Type of relationship as used in the citation.', max_length=255),
        ),
        migrations.AlterField(
            model_name='citation',
            name='abstract',
            field=models.TextField(blank=True, help_text=b'Abstract or detailed summaries of a work.'),
        ),
        migrations.AlterField(
            model_name='citation',
            name='administrator_notes',
            field=models.TextField(blank=True, help_text=b'Curatorial discussion about the record.', null=True),
        ),
        migrations.AlterField(
            model_name='citation',
            name='created_by_fm',
            field=models.CharField(blank=True, help_text=b'Value of CreatedBy from the original FM database.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='citation',
            name='created_on_fm',
            field=models.DateTimeField(help_text=b'Value of CreatedOn from the original FM database.', null=True),
        ),
        migrations.AlterField(
            model_name='citation',
            name='description',
            field=models.TextField(blank=True, help_text=b"Used for additional bibliographic description, such as content summary. For abstracts use the 'Abstract' field.", null=True),
        ),
        migrations.AlterField(
            model_name='citation',
            name='edition_details',
            field=models.TextField(blank=True, help_text=b'Use for describing the edition or version of the resource. Include names of additional contributors if necessary for clarification (such as translators, introduction by, etc). Always, use relationship table to list contributors (even if they are specified here).'),
        ),
        migrations.AlterField(
            model_name='citation',
            name='id',
            field=models.CharField(help_text=b'In the format {PRE}{ZEROS}{NN}, where PRE is a three-letter prefix indicating the record type (e.g. CBA for Authority), NN is an integer, and ZEROS is 0-9 zeros to pad NN such that ZEROS+NN is nine characters in length.', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='citation',
            name='language',
            field=models.ManyToManyField(help_text=b'Language of the resource. Multiple languages can be specified.', to='isisdata.Language'),
        ),
        migrations.AlterField(
            model_name='citation',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text=b'The most recent user to modify this object.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='citation',
            name='modified_by_fm',
            field=models.CharField(blank=True, help_text=b'Value of ModifiedOn from the original FM database.', max_length=255, verbose_name=b'modified by (FM)'),
        ),
        migrations.AlterField(
            model_name='citation',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, help_text=b'Date and time at which this object was last updated.', null=True),
        ),
        migrations.AlterField(
            model_name='citation',
            name='modified_on_fm',
            field=models.DateTimeField(help_text=b'Value of ModifiedBy from the original FM database.', null=True, verbose_name=b'modified on (FM)'),
        ),
        migrations.AlterField(
            model_name='citation',
            name='part_details',
            field=models.OneToOneField(blank=True, help_text=b'New field: contains volume, issue, page information for works that are parts of larger works.', null=True, on_delete=django.db.models.deletion.CASCADE, to='isisdata.PartDetails'),
        ),
        migrations.AlterField(
            model_name='citation',
            name='physical_details',
            field=models.CharField(blank=True, help_text=b'For describing the physical description of the resource. Use whatever information is appropriate for the type of resource.', max_length=255),
        ),
        migrations.AlterField(
            model_name='citation',
            name='public',
            field=models.BooleanField(default=True, help_text=b'Controls whether this instance can be viewed by end users.'),
        ),
        migrations.AlterField(
            model_name='citation',
            name='publication_date',
            field=models.DateField(blank=True, help_text=b'Used for search and sort functionality. Does not replace Attribute functionality.', null=True),
        ),
        migrations.AlterField(
            model_name='citation',
            name='record_action',
            field=models.CharField(blank=True, choices=[(b'EX', b'External Proof'), (b'QU', b'Query Proof'), (b'HO', b'Hold'), (b'RC', b'RLG Correct')], help_text=b'Used to track the record through curation process.', max_length=2),
        ),
        migrations.AlterField(
            model_name='citation',
            name='record_history',
            field=models.TextField(blank=True, help_text=b"Notes about the provenance of the information in this record. e.g. 'supplied by the author,' 'imported from SHOT bibliography,' 'generated by crawling UC Press website'", null=True),
        ),
        migrations.AlterField(
            model_name='citation',
            name='title',
            field=models.CharField(blank=True, help_text=b'The name to be used to identify the resource. For reviews that traditionally have no title, this should be added as something like "[Review of Title (Year) by Author]".', max_length=2000),
        ),
        migrations.AlterField(
            model_name='citation',
            name='type_controlled',
            field=models.CharField(blank=True, choices=[(b'BO', b'Book'), (b'AR', b'Article'), (b'CH', b'Chapter'), (b'RE', b'Review'), (b'ES', b'Essay Review'), (b'TH', b'Thesis'), (b'EV', b'Event'), (b'PR', b'Presentation'), (b'IN', b'Interactive Resource'), (b'WE', b'Website'), (b'AP', b'Application')], help_text=b'This list can be extended to the resource types specified by Doublin Core Recource Types http://dublincore.org/documents/resource-typelist/', max_length=2, null=True, verbose_name=b'type'),
        ),
        migrations.AlterField(
            model_name='historicalacrelation',
            name='administrator_notes',
            field=models.TextField(blank=True, help_text=b'Curatorial discussion about the record.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalacrelation',
            name='confidence_measure',
            field=models.FloatField(default=1.0, help_text=b'Currently not used: will be used to assess the confidence of the link in the event that there is some ambiguity.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='historicalacrelation',
            name='created_by_fm',
            field=models.CharField(blank=True, help_text=b'Value of CreatedBy from the original FM database.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalacrelation',
            name='created_on_fm',
            field=models.DateTimeField(help_text=b'Value of CreatedOn from the original FM database.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalacrelation',
            name='data_display_order',
            field=models.FloatField(default=1.0, help_text=b'Position at which the authority should be displayed in the citation detail view. Whole numbers or decimals can be used.'),
        ),
        migrations.AlterField(
            model_name='historicalacrelation',
            name='id',
            field=models.CharField(db_index=True, help_text=b'In the format {PRE}{ZEROS}{NN}, where PRE is a three-letter prefix indicating the record type (e.g. CBA for Authority), NN is an integer, and ZEROS is 0-9 zeros to pad NN such that ZEROS+NN is nine characters in length.', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalacrelation',
            name='modified_by_fm',
            field=models.CharField(blank=True, help_text=b'Value of ModifiedOn from the original FM database.', max_length=255, verbose_name=b'modified by (FM)'),
        ),
        migrations.AlterField(
            model_name='historicalacrelation',
            name='modified_on',
            field=models.DateTimeField(blank=True, editable=False, help_text=b'Date and time at which this object was last updated.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalacrelation',
            name='modified_on_fm',
            field=models.DateTimeField(help_text=b'Value of ModifiedBy from the original FM database.', null=True, verbose_name=b'modified on (FM)'),
        ),
        migrations.AlterField(
            model_name='historicalacrelation',
            name='name_as_entered',
            field=models.CharField(blank=True, help_text=b'Display for the authority as it is has been used in a publication.', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalacrelation',
            name='name_for_display_in_citation',
            field=models.CharField(help_text=b"Display for the authority as it is to be used when being displayed with the citation. Eg. the form of the author's name as it appears on a publication--say, J.E. Koval--which might be different from the name of the authority--Jenifer Elizabeth Koval.", max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalacrelation',
            name='public',
            field=models.BooleanField(default=True, help_text=b'Controls whether this instance can be viewed by end users.'),
        ),
        migrations.AlterField(
            model_name='historicalacrelation',
            name='record_history',
            field=models.TextField(blank=True, help_text=b"Notes about the provenance of the information in this record. e.g. 'supplied by the author,' 'imported from SHOT bibliography,' 'generated by crawling UC Press website'", null=True),
        ),
        migrations.AlterField(
            model_name='historicalacrelation',
            name='relationship_weight',
            field=models.FloatField(default=1.0, help_text=b'Currently not used: helps to assess how significant this relationship is--to be used mostly in marking subjects.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='historicalacrelation',
            name='type_broad_controlled',
            field=models.CharField(blank=True, choices=[(b'PR', b'Has Personal Responsibility For'), (b'SC', b'Provides Subject Content About'), (b'IH', b'Is Institutional Host Of'), (b'PH', b'Is Publication Host Of')], help_text=b'Used to specify the nature of the relationship between authority (as the subject) and the citation (as the object) more broadly than the relationship type.', max_length=2, verbose_name=b'relationship type (broad)'),
        ),
        migrations.AlterField(
            model_name='historicalacrelation',
            name='type_controlled',
            field=models.CharField(blank=True, choices=[(b'AU', b'Author'), (b'ED', b'Editor'), (b'AD', b'Advisor'), (b'CO', b'Contributor'), (b'TR', b'Translator'), (b'SU', b'Subject'), (b'CA', b'Category'), (b'PU', b'Publisher'), (b'SC', b'School'), (b'IN', b'Institution'), (b'ME', b'Meeting'), (b'PE', b'Periodical'), (b'BS', b'Book Series')], help_text=b'Used to specify the nature of the relationship between authority (as the subject) and the citation (as the object).', max_length=2, null=True, verbose_name=b'relationship type'),
        ),
        migrations.AlterField(
            model_name='historicalacrelation',
            name='type_free',
            field=models.CharField(blank=True, help_text=b"\n    Free-text description of the role that the authority plays in the\n    citation (e.g. 'introduction by', 'dissertation supervisor', etc).\n    ", max_length=255, verbose_name=b'relationship type (free-text)'),
        ),
        migrations.AlterField(
            model_name='historicalattribute',
            name='administrator_notes',
            field=models.TextField(blank=True, help_text=b'Curatorial discussion about the record.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalattribute',
            name='created_by_fm',
            field=models.CharField(blank=True, help_text=b'Value of CreatedBy from the original FM database.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalattribute',
            name='created_on_fm',
            field=models.DateTimeField(help_text=b'Value of CreatedOn from the original FM database.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalattribute',
            name='description',
            field=models.TextField(blank=True, help_text=b'Additional information about this attribute.'),
        ),
        migrations.AlterField(
            model_name='historicalattribute',
            name='id',
            field=models.CharField(db_index=True, help_text=b'In the format {PRE}{ZEROS}{NN}, where PRE is a three-letter prefix indicating the record type (e.g. CBA for Authority), NN is an integer, and ZEROS is 0-9 zeros to pad NN such that ZEROS+NN is nine characters in length.', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalattribute',
            name='modified_by_fm',
            field=models.CharField(blank=True, help_text=b'Value of ModifiedOn from the original FM database.', max_length=255, verbose_name=b'modified by (FM)'),
        ),
        migrations.AlterField(
            model_name='historicalattribute',
            name='modified_on',
            field=models.DateTimeField(blank=True, editable=False, help_text=b'Date and time at which this object was last updated.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalattribute',
            name='modified_on_fm',
            field=models.DateTimeField(help_text=b'Value of ModifiedBy from the original FM database.', null=True, verbose_name=b'modified on (FM)'),
        ),
        migrations.AlterField(
            model_name='historicalattribute',
            name='public',
            field=models.BooleanField(default=True, help_text=b'Controls whether this instance can be viewed by end users.'),
        ),
        migrations.AlterField(
            model_name='historicalattribute',
            name='record_history',
            field=models.TextField(blank=True, help_text=b"Notes about the provenance of the information in this record. e.g. 'supplied by the author,' 'imported from SHOT bibliography,' 'generated by crawling UC Press website'", null=True),
        ),
        migrations.AlterField(
            model_name='historicalattribute',
            name='value_freeform',
            field=models.CharField(blank=True, help_text=b'Non-normalized value, e.g. an approximate date, or a date range.', max_length=255, verbose_name=b'freeform value'),
        ),
        migrations.AlterField(
            model_name='historicalauthority',
            name='administrator_notes',
            field=models.TextField(blank=True, help_text=b'Curatorial discussion about the record.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalauthority',
            name='classification_code',
            field=models.CharField(blank=True, help_text=b'alphanumeric code used in previous classification systems to describe classification terms. Primarily of historical interest only. Used primarily for Codes for the classificationTerms. however, can be used for other kinds of terms as appropriate.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalauthority',
            name='classification_hierarchy',
            field=models.CharField(blank=True, help_text=b'Used for Classification Terms to describe where they fall in the hierarchy.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalauthority',
            name='classification_system',
            field=models.CharField(blank=True, choices=[(b'SWP', b'SWP'), (b'NEU', b'Neu'), (b'MW', b'MW'), (b'SHOT', b'SHOT'), (b'SAC', b'SAC')], help_text=b'Specifies the classification system that is the source of the authority. Used to group resources by the Classification system. The system used currently is the Weldon System. All the other ones are for reference or archival purposes only.', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='historicalauthority',
            name='created_by_fm',
            field=models.CharField(blank=True, help_text=b'Value of CreatedBy from the original FM database.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalauthority',
            name='created_on_fm',
            field=models.DateTimeField(help_text=b'Value of CreatedOn from the original FM database.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalauthority',
            name='description',
            field=models.TextField(blank=True, help_text=b"A brief description that will be displayed to help identify the authority. Such as, brief bio or a scope note. For classification terms will be text like 'Classification term from the XXX classification schema.'", null=True),
        ),
        migrations.AlterField(
            model_name='historicalauthority',
            name='id',
            field=models.CharField(db_index=True, help_text=b'In the format {PRE}{ZEROS}{NN}, where PRE is a three-letter prefix indicating the record type (e.g. CBA for Authority), NN is an integer, and ZEROS is 0-9 zeros to pad NN such that ZEROS+NN is nine characters in length.', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalauthority',
            name='modified_by_fm',
            field=models.CharField(blank=True, help_text=b'Value of ModifiedOn from the original FM database.', max_length=255, verbose_name=b'modified by (FM)'),
        ),
        migrations.AlterField(
            model_name='historicalauthority',
            name='modified_on',
            field=models.DateTimeField(blank=True, editable=False, help_text=b'Date and time at which this object was last updated.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalauthority',
            name='modified_on_fm',
            field=models.DateTimeField(help_text=b'Value of ModifiedBy from the original FM database.', null=True, verbose_name=b'modified on (FM)'),
        ),
        migrations.AlterField(
            model_name='historicalauthority',
            name='name',
            field=models.CharField(help_text=b'Name, title, or other main term for the authority as will be displayed.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='historicalauthority',
            name='public',
            field=models.BooleanField(default=True, help_text=b'Controls whether this instance can be viewed by end users.'),
        ),
        migrations.AlterField(
            model_name='historicalauthority',
            name='record_history',
            field=models.TextField(blank=True, help_text=b"Notes about the provenance of the information in this record. e.g. 'supplied by the author,' 'imported from SHOT bibliography,' 'generated by crawling UC Press website'", null=True),
        ),
        migrations.AlterField(
            model_name='historicalauthority',
            name='type_controlled',
            field=models.CharField(blank=True, choices=[(b'PE', b'Person'), (b'IN', b'Institution'), (b'TI', b'Time Period'), (b'GE', b'Geographic Term'), (b'SE', b'Serial Publication'), (b'CT', b'Classification Term'), (b'CO', b'Concept'), (b'CW', b'Creative Work'), (b'EV', b'Event'), (b'CR', b'Cross-reference'), (b'PU', b'Publisher')], help_text=b'Specifies authority type. Each authority thema has its own list of controlled type vocabulary.', max_length=2, null=True, verbose_name=b'type'),
        ),
        migrations.AlterField(
            model_name='historicalccrelation',
            name='administrator_notes',
            field=models.TextField(blank=True, help_text=b'Curatorial discussion about the record.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalccrelation',
            name='created_by_fm',
            field=models.CharField(blank=True, help_text=b'Value of CreatedBy from the original FM database.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalccrelation',
            name='created_on_fm',
            field=models.DateTimeField(help_text=b'Value of CreatedOn from the original FM database.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalccrelation',
            name='id',
            field=models.CharField(db_index=True, help_text=b'In the format {PRE}{ZEROS}{NN}, where PRE is a three-letter prefix indicating the record type (e.g. CBA for Authority), NN is an integer, and ZEROS is 0-9 zeros to pad NN such that ZEROS+NN is nine characters in length.', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalccrelation',
            name='modified_by_fm',
            field=models.CharField(blank=True, help_text=b'Value of ModifiedOn from the original FM database.', max_length=255, verbose_name=b'modified by (FM)'),
        ),
        migrations.AlterField(
            model_name='historicalccrelation',
            name='modified_on',
            field=models.DateTimeField(blank=True, editable=False, help_text=b'Date and time at which this object was last updated.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalccrelation',
            name='modified_on_fm',
            field=models.DateTimeField(help_text=b'Value of ModifiedBy from the original FM database.', null=True, verbose_name=b'modified on (FM)'),
        ),
        migrations.AlterField(
            model_name='historicalccrelation',
            name='public',
            field=models.BooleanField(default=True, help_text=b'Controls whether this instance can be viewed by end users.'),
        ),
        migrations.AlterField(
            model_name='historicalccrelation',
            name='record_history',
            field=models.TextField(blank=True, help_text=b"Notes about the provenance of the information in this record. e.g. 'supplied by the author,' 'imported from SHOT bibliography,' 'generated by crawling UC Press website'", null=True),
        ),
        migrations.AlterField(
            model_name='historicalccrelation',
            name='type_controlled',
            field=models.CharField(blank=True, choices=[(b'IC', b'Includes Chapter'), (b'ISA', b'Includes Series Article'), (b'RO', b'Is Review Of'), (b'RE', b'Responds To'), (b'AS', b'Is Associated With'), (b'RB', b'Is Reviewed By')], help_text=b'Type of relationship between two citation records.', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='historicalccrelation',
            name='type_free',
            field=models.CharField(blank=True, help_text=b'Type of relationship as used in the citation.', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalcitation',
            name='abstract',
            field=models.TextField(blank=True, help_text=b'Abstract or detailed summaries of a work.'),
        ),
        migrations.AlterField(
            model_name='historicalcitation',
            name='administrator_notes',
            field=models.TextField(blank=True, help_text=b'Curatorial discussion about the record.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcitation',
            name='created_by_fm',
            field=models.CharField(blank=True, help_text=b'Value of CreatedBy from the original FM database.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcitation',
            name='created_on_fm',
            field=models.DateTimeField(help_text=b'Value of CreatedOn from the original FM database.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcitation',
            name='description',
            field=models.TextField(blank=True, help_text=b"Used for additional bibliographic description, such as content summary. For abstracts use the 'Abstract' field.", null=True),
        ),
        migrations.AlterField(
            model_name='historicalcitation',
            name='edition_details',
            field=models.TextField(blank=True, help_text=b'Use for describing the edition or version of the resource. Include names of additional contributors if necessary for clarification (such as translators, introduction by, etc). Always, use relationship table to list contributors (even if they are specified here).'),
        ),
        migrations.AlterField(
            model_name='historicalcitation',
            name='id',
            field=models.CharField(db_index=True, help_text=b'In the format {PRE}{ZEROS}{NN}, where PRE is a three-letter prefix indicating the record type (e.g. CBA for Authority), NN is an integer, and ZEROS is 0-9 zeros to pad NN such that ZEROS+NN is nine characters in length.', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalcitation',
            name='modified_by_fm',
            field=models.CharField(blank=True, help_text=b'Value of ModifiedOn from the original FM database.', max_length=255, verbose_name=b'modified by (FM)'),
        ),
        migrations.AlterField(
            model_name='historicalcitation',
            name='modified_on',
            field=models.DateTimeField(blank=True, editable=False, help_text=b'Date and time at which this object was last updated.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcitation',
            name='modified_on_fm',
            field=models.DateTimeField(help_text=b'Value of ModifiedBy from the original FM database.', null=True, verbose_name=b'modified on (FM)'),
        ),
        migrations.AlterField(
            model_name='historicalcitation',
            name='physical_details',
            field=models.CharField(blank=True, help_text=b'For describing the physical description of the resource. Use whatever information is appropriate for the type of resource.', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalcitation',
            name='public',
            field=models.BooleanField(default=True, help_text=b'Controls whether this instance can be viewed by end users.'),
        ),
        migrations.AlterField(
            model_name='historicalcitation',
            name='publication_date',
            field=models.DateField(blank=True, help_text=b'Used for search and sort functionality. Does not replace Attribute functionality.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcitation',
            name='record_action',
            field=models.CharField(blank=True, choices=[(b'EX', b'External Proof'), (b'QU', b'Query Proof'), (b'HO', b'Hold'), (b'RC', b'RLG Correct')], help_text=b'Used to track the record through curation process.', max_length=2),
        ),
        migrations.AlterField(
            model_name='historicalcitation',
            name='record_history',
            field=models.TextField(blank=True, help_text=b"Notes about the provenance of the information in this record. e.g. 'supplied by the author,' 'imported from SHOT bibliography,' 'generated by crawling UC Press website'", null=True),
        ),
        migrations.AlterField(
            model_name='historicalcitation',
            name='title',
            field=models.CharField(blank=True, help_text=b'The name to be used to identify the resource. For reviews that traditionally have no title, this should be added as something like "[Review of Title (Year) by Author]".', max_length=2000),
        ),
        migrations.AlterField(
            model_name='historicalcitation',
            name='type_controlled',
            field=models.CharField(blank=True, choices=[(b'BO', b'Book'), (b'AR', b'Article'), (b'CH', b'Chapter'), (b'RE', b'Review'), (b'ES', b'Essay Review'), (b'TH', b'Thesis'), (b'EV', b'Event'), (b'PR', b'Presentation'), (b'IN', b'Interactive Resource'), (b'WE', b'Website'), (b'AP', b'Application')], help_text=b'This list can be extended to the resource types specified by Doublin Core Recource Types http://dublincore.org/documents/resource-typelist/', max_length=2, null=True, verbose_name=b'type'),
        ),
        migrations.AlterField(
            model_name='historicallinkeddata',
            name='administrator_notes',
            field=models.TextField(blank=True, help_text=b'Curatorial discussion about the record.', null=True),
        ),
        migrations.AlterField(
            model_name='historicallinkeddata',
            name='created_by_fm',
            field=models.CharField(blank=True, help_text=b'Value of CreatedBy from the original FM database.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicallinkeddata',
            name='created_on_fm',
            field=models.DateTimeField(help_text=b'Value of CreatedOn from the original FM database.', null=True),
        ),
        migrations.AlterField(
            model_name='historicallinkeddata',
            name='id',
            field=models.CharField(db_index=True, help_text=b'In the format {PRE}{ZEROS}{NN}, where PRE is a three-letter prefix indicating the record type (e.g. CBA for Authority), NN is an integer, and ZEROS is 0-9 zeros to pad NN such that ZEROS+NN is nine characters in length.', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicallinkeddata',
            name='modified_by_fm',
            field=models.CharField(blank=True, help_text=b'Value of ModifiedOn from the original FM database.', max_length=255, verbose_name=b'modified by (FM)'),
        ),
        migrations.AlterField(
            model_name='historicallinkeddata',
            name='modified_on',
            field=models.DateTimeField(blank=True, editable=False, help_text=b'Date and time at which this object was last updated.', null=True),
        ),
        migrations.AlterField(
            model_name='historicallinkeddata',
            name='modified_on_fm',
            field=models.DateTimeField(help_text=b'Value of ModifiedBy from the original FM database.', null=True, verbose_name=b'modified on (FM)'),
        ),
        migrations.AlterField(
            model_name='historicallinkeddata',
            name='public',
            field=models.BooleanField(default=True, help_text=b'Controls whether this instance can be viewed by end users.'),
        ),
        migrations.AlterField(
            model_name='historicallinkeddata',
            name='record_history',
            field=models.TextField(blank=True, help_text=b"Notes about the provenance of the information in this record. e.g. 'supplied by the author,' 'imported from SHOT bibliography,' 'generated by crawling UC Press website'", null=True),
        ),
        migrations.AlterField(
            model_name='historicallinkeddata',
            name='universal_resource_name',
            field=models.CharField(help_text=b'The value of the identifier (the actual DOI link or the value of the ISBN, etc). Will be a URN, URI, URL, or other unique identifier for a work, used as needed to provide information about how to find the digital object on the web or to identify the physical object uniquely.', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='administrator_notes',
            field=models.TextField(blank=True, help_text=b'Curatorial discussion about the record.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='classification_code',
            field=models.CharField(blank=True, help_text=b'alphanumeric code used in previous classification systems to describe classification terms. Primarily of historical interest only. Used primarily for Codes for the classificationTerms. however, can be used for other kinds of terms as appropriate.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='classification_hierarchy',
            field=models.CharField(blank=True, help_text=b'Used for Classification Terms to describe where they fall in the hierarchy.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='classification_system',
            field=models.CharField(blank=True, choices=[(b'SWP', b'SWP'), (b'NEU', b'Neu'), (b'MW', b'MW'), (b'SHOT', b'SHOT'), (b'SAC', b'SAC')], help_text=b'Specifies the classification system that is the source of the authority. Used to group resources by the Classification system. The system used currently is the Weldon System. All the other ones are for reference or archival purposes only.', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='created_by_fm',
            field=models.CharField(blank=True, help_text=b'Value of CreatedBy from the original FM database.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='created_on_fm',
            field=models.DateTimeField(help_text=b'Value of CreatedOn from the original FM database.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='description',
            field=models.TextField(blank=True, help_text=b"A brief description that will be displayed to help identify the authority. Such as, brief bio or a scope note. For classification terms will be text like 'Classification term from the XXX classification schema.'", null=True),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='id',
            field=models.CharField(db_index=True, help_text=b'In the format {PRE}{ZEROS}{NN}, where PRE is a three-letter prefix indicating the record type (e.g. CBA for Authority), NN is an integer, and ZEROS is 0-9 zeros to pad NN such that ZEROS+NN is nine characters in length.', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='modified_by_fm',
            field=models.CharField(blank=True, help_text=b'Value of ModifiedOn from the original FM database.', max_length=255, verbose_name=b'modified by (FM)'),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='modified_on',
            field=models.DateTimeField(blank=True, editable=False, help_text=b'Date and time at which this object was last updated.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='modified_on_fm',
            field=models.DateTimeField(help_text=b'Value of ModifiedBy from the original FM database.', null=True, verbose_name=b'modified on (FM)'),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='name',
            field=models.CharField(help_text=b'Name, title, or other main term for the authority as will be displayed.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='public',
            field=models.BooleanField(default=True, help_text=b'Controls whether this instance can be viewed by end users.'),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='record_history',
            field=models.TextField(blank=True, help_text=b"Notes about the provenance of the information in this record. e.g. 'supplied by the author,' 'imported from SHOT bibliography,' 'generated by crawling UC Press website'", null=True),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='type_controlled',
            field=models.CharField(blank=True, choices=[(b'PE', b'Person'), (b'IN', b'Institution'), (b'TI', b'Time Period'), (b'GE', b'Geographic Term'), (b'SE', b'Serial Publication'), (b'CT', b'Classification Term'), (b'CO', b'Concept'), (b'CW', b'Creative Work'), (b'EV', b'Event'), (b'CR', b'Cross-reference'), (b'PU', b'Publisher')], help_text=b'Specifies authority type. Each authority thema has its own list of controlled type vocabulary.', max_length=2, null=True, verbose_name=b'type'),
        ),
        migrations.AlterField(
            model_name='historicaltracking',
            name='administrator_notes',
            field=models.TextField(blank=True, help_text=b'Curatorial discussion about the record.', null=True),
        ),
        migrations.AlterField(
            model_name='historicaltracking',
            name='created_by_fm',
            field=models.CharField(blank=True, help_text=b'Value of CreatedBy from the original FM database.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltracking',
            name='created_on_fm',
            field=models.DateTimeField(help_text=b'Value of CreatedOn from the original FM database.', null=True),
        ),
        migrations.AlterField(
            model_name='historicaltracking',
            name='id',
            field=models.CharField(db_index=True, help_text=b'In the format {PRE}{ZEROS}{NN}, where PRE is a three-letter prefix indicating the record type (e.g. CBA for Authority), NN is an integer, and ZEROS is 0-9 zeros to pad NN such that ZEROS+NN is nine characters in length.', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicaltracking',
            name='modified_by_fm',
            field=models.CharField(blank=True, help_text=b'Value of ModifiedOn from the original FM database.', max_length=255, verbose_name=b'modified by (FM)'),
        ),
        migrations.AlterField(
            model_name='historicaltracking',
            name='modified_on',
            field=models.DateTimeField(blank=True, editable=False, help_text=b'Date and time at which this object was last updated.', null=True),
        ),
        migrations.AlterField(
            model_name='historicaltracking',
            name='modified_on_fm',
            field=models.DateTimeField(help_text=b'Value of ModifiedBy from the original FM database.', null=True, verbose_name=b'modified on (FM)'),
        ),
        migrations.AlterField(
            model_name='historicaltracking',
            name='public',
            field=models.BooleanField(default=True, help_text=b'Controls whether this instance can be viewed by end users.'),
        ),
        migrations.AlterField(
            model_name='historicaltracking',
            name='record_history',
            field=models.TextField(blank=True, help_text=b"Notes about the provenance of the information in this record. e.g. 'supplied by the author,' 'imported from SHOT bibliography,' 'generated by crawling UC Press website'", null=True),
        ),
        migrations.AlterField(
            model_name='linkeddata',
            name='administrator_notes',
            field=models.TextField(blank=True, help_text=b'Curatorial discussion about the record.', null=True),
        ),
        migrations.AlterField(
            model_name='linkeddata',
            name='created_by_fm',
            field=models.CharField(blank=True, help_text=b'Value of CreatedBy from the original FM database.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='linkeddata',
            name='created_on_fm',
            field=models.DateTimeField(help_text=b'Value of CreatedOn from the original FM database.', null=True),
        ),
        migrations.AlterField(
            model_name='linkeddata',
            name='id',
            field=models.CharField(help_text=b'In the format {PRE}{ZEROS}{NN}, where PRE is a three-letter prefix indicating the record type (e.g. CBA for Authority), NN is an integer, and ZEROS is 0-9 zeros to pad NN such that ZEROS+NN is nine characters in length.', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='linkeddata',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text=b'The most recent user to modify this object.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='linkeddata',
            name='modified_by_fm',
            field=models.CharField(blank=True, help_text=b'Value of ModifiedOn from the original FM database.', max_length=255, verbose_name=b'modified by (FM)'),
        ),
        migrations.AlterField(
            model_name='linkeddata',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, help_text=b'Date and time at which this object was last updated.', null=True),
        ),
        migrations.AlterField(
            model_name='linkeddata',
            name='modified_on_fm',
            field=models.DateTimeField(help_text=b'Value of ModifiedBy from the original FM database.', null=True, verbose_name=b'modified on (FM)'),
        ),
        migrations.AlterField(
            model_name='linkeddata',
            name='public',
            field=models.BooleanField(default=True, help_text=b'Controls whether this instance can be viewed by end users.'),
        ),
        migrations.AlterField(
            model_name='linkeddata',
            name='record_history',
            field=models.TextField(blank=True, help_text=b"Notes about the provenance of the information in this record. e.g. 'supplied by the author,' 'imported from SHOT bibliography,' 'generated by crawling UC Press website'", null=True),
        ),
        migrations.AlterField(
            model_name='linkeddata',
            name='type_controlled',
            field=models.ForeignKey(help_text=b'The "type" field determines what kinds of values are acceptable for this linked data entry.', on_delete=django.db.models.deletion.CASCADE, to='isisdata.LinkedDataType', verbose_name=b'type'),
        ),
        migrations.AlterField(
            model_name='linkeddata',
            name='universal_resource_name',
            field=models.CharField(help_text=b'The value of the identifier (the actual DOI link or the value of the ISBN, etc). Will be a URN, URI, URL, or other unique identifier for a work, used as needed to provide information about how to find the digital object on the web or to identify the physical object uniquely.', max_length=255),
        ),
        migrations.AlterField(
            model_name='linkeddatatype',
            name='pattern',
            field=models.CharField(blank=True, help_text=b'Regular expression used to validate :class:`.LinkedData` values.', max_length=255),
        ),
        migrations.AlterField(
            model_name='partdetails',
            name='sort_order',
            field=models.IntegerField(default=0, help_text=b'" New field: provides a sort order for works that are part of a larger work.'),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='name',
            field=models.CharField(blank=True, help_text=b'Provide a memorable name so that you can find this search later.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='administrator_notes',
            field=models.TextField(blank=True, help_text=b'Curatorial discussion about the record.', null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='created_by_fm',
            field=models.CharField(blank=True, help_text=b'Value of CreatedBy from the original FM database.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='created_on_fm',
            field=models.DateTimeField(help_text=b'Value of CreatedOn from the original FM database.', null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='id',
            field=models.CharField(help_text=b'In the format {PRE}{ZEROS}{NN}, where PRE is a three-letter prefix indicating the record type (e.g. CBA for Authority), NN is an integer, and ZEROS is 0-9 zeros to pad NN such that ZEROS+NN is nine characters in length.', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text=b'The most recent user to modify this object.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='modified_by_fm',
            field=models.CharField(blank=True, help_text=b'Value of ModifiedOn from the original FM database.', max_length=255, verbose_name=b'modified by (FM)'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, help_text=b'Date and time at which this object was last updated.', null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='modified_on_fm',
            field=models.DateTimeField(help_text=b'Value of ModifiedBy from the original FM database.', null=True, verbose_name=b'modified on (FM)'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='public',
            field=models.BooleanField(default=True, help_text=b'Controls whether this instance can be viewed by end users.'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='record_history',
            field=models.TextField(blank=True, help_text=b"Notes about the provenance of the information in this record. e.g. 'supplied by the author,' 'imported from SHOT bibliography,' 'generated by crawling UC Press website'", null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='attribute',
            field=models.OneToOneField(help_text=b'The Attribute to which this Value belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='value', to='isisdata.Attribute'),
        ),
        migrations.AlterField(
            model_name='value',
            name='child_class',
            field=models.CharField(help_text=b'Name of the child model for this instance.', max_length=255),
        ),
    ]
