# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0013_auto_20160322_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acrelation',
            name='authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='isisdata.Authority'),
        ),
    ]
