# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0015_auto_20160424_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citation',
            name='abstract',
            field=models.TextField(blank=True, help_text=b'Abstract or detailed summaries of a work.', null=True),
        ),
        migrations.AlterField(
            model_name='citation',
            name='edition_details',
            field=models.TextField(blank=True, help_text=b'Use for describing the edition or version of the resource. Include names of additional contributors if necessary for clarification (such as translators, introduction by, etc). Always, use relationship table to list contributors (even if they are specified here).', null=True),
        ),
        migrations.AlterField(
            model_name='citation',
            name='physical_details',
            field=models.CharField(blank=True, help_text=b'For describing the physical description of the resource. Use whatever information is appropriate for the type of resource.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcitation',
            name='abstract',
            field=models.TextField(blank=True, help_text=b'Abstract or detailed summaries of a work.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcitation',
            name='edition_details',
            field=models.TextField(blank=True, help_text=b'Use for describing the edition or version of the resource. Include names of additional contributors if necessary for clarification (such as translators, introduction by, etc). Always, use relationship table to list contributors (even if they are specified here).', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcitation',
            name='physical_details',
            field=models.CharField(blank=True, help_text=b'For describing the physical description of the resource. Use whatever information is appropriate for the type of resource.', max_length=255, null=True),
        ),
    ]
