# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0016_auto_20160424_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acrelation',
            name='name_as_entered',
            field=models.CharField(blank=True, help_text=b'Display for the authority as it is has been used in a publication.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='acrelation',
            name='name_for_display_in_citation',
            field=models.CharField(blank=True, help_text=b"Display for the authority as it is to be used when being displayed with the citation. Eg. the form of the author's name as it appears on a publication--say, J.E. Koval--which might be different from the name of the authority--Jenifer Elizabeth Koval.", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='citation',
            name='language',
            field=models.ManyToManyField(blank=True, help_text=b'Language of the resource. Multiple languages can be specified.', null=True, to='isisdata.Language'),
        ),
        migrations.AlterField(
            model_name='historicalacrelation',
            name='name_as_entered',
            field=models.CharField(blank=True, help_text=b'Display for the authority as it is has been used in a publication.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalacrelation',
            name='name_for_display_in_citation',
            field=models.CharField(blank=True, help_text=b"Display for the authority as it is to be used when being displayed with the citation. Eg. the form of the author's name as it appears on a publication--say, J.E. Koval--which might be different from the name of the authority--Jenifer Elizabeth Koval.", max_length=255, null=True),
        ),
    ]
