# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0017_auto_20160424_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='classification_system',
            field=models.CharField(blank=True, choices=[(b'SWP', b'SWP'), (b'NEU', b'Neu'), (b'MW', b'MW'), (b'SHOT', b'SHOT'), (b'SAC', b'SAC')], default=b'SWP', help_text=b'Specifies the classification system that is the source of the authority. Used to group resources by the Classification system. The system used currently is the Weldon System. All the other ones are for reference or archival purposes only.', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='historicalauthority',
            name='classification_system',
            field=models.CharField(blank=True, choices=[(b'SWP', b'SWP'), (b'NEU', b'Neu'), (b'MW', b'MW'), (b'SHOT', b'SHOT'), (b'SAC', b'SAC')], default=b'SWP', help_text=b'Specifies the classification system that is the source of the authority. Used to group resources by the Classification system. The system used currently is the Weldon System. All the other ones are for reference or archival purposes only.', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='classification_system',
            field=models.CharField(blank=True, choices=[(b'SWP', b'SWP'), (b'NEU', b'Neu'), (b'MW', b'MW'), (b'SHOT', b'SHOT'), (b'SAC', b'SAC')], default=b'SWP', help_text=b'Specifies the classification system that is the source of the authority. Used to group resources by the Classification system. The system used currently is the Weldon System. All the other ones are for reference or archival purposes only.', max_length=4, null=True),
        ),
    ]
