# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-16 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0020_auto_20160615_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccrelation',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relations_to', to='isisdata.Citation'),
        ),
        migrations.AlterField(
            model_name='ccrelation',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relations_from', to='isisdata.Citation'),
        ),
    ]
