# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-23 23:16
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0024_auto_20160623_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISODateRangeValue',
            fields=[
                ('value_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='isisdata.Value')),
                ('start', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=3)),
                ('end', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=3)),
            ],
            options={
                'verbose_name': 'date range',
            },
            bases=('isisdata.value',),
        ),
    ]
