# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0056_auto_20170309_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltracking',
            name='type_controlled',
            field=models.CharField(blank=True, choices=[(b'HS', b'HSTM Upload'), (b'PT', b'Printed'), (b'AU', b'Authorized'), (b'PD', b'Proofed'), (b'FU', b'Fully Entered'), (b'BD', b'Bulk Data Update')], db_index=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='type_controlled',
            field=models.CharField(blank=True, choices=[(b'HS', b'HSTM Upload'), (b'PT', b'Printed'), (b'AU', b'Authorized'), (b'PD', b'Proofed'), (b'FU', b'Fully Entered'), (b'BD', b'Bulk Data Update')], db_index=True, max_length=2, null=True),
        ),
    ]
