# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0057_auto_20170324_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltracking',
            name='citation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='isisdata.Citation'),
        ),
        migrations.AddField(
            model_name='tracking',
            name='citation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_records', to='isisdata.Citation'),
        ),
    ]
