# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 17:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zotero', '0018_auto_20170205_2354'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('isisdata', '0058_auto_20170324_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityTracking',
            fields=[
                ('administrator_notes', models.TextField(blank=True, help_text=b'Curatorial discussion about the record.', null=True)),
                ('record_history', models.TextField(blank=True, help_text=b"Notes about the provenance of the information in this record. e.g. 'supplied by the author,' 'imported from SHOT bibliography,' 'generated by crawling UC Press website'", null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, help_text=b'Date and time at which this object was last updated.', null=True)),
                ('public', models.BooleanField(default=True, help_text=b'Controls whether this instance can be viewed by end users.')),
                ('record_status_value', models.CharField(blank=True, choices=[(b'Active', b'Active'), (b'Duplicate', b'Duplicate'), (b'Redirect', b'Redirect'), (b'Inactive', b'Inactive')], default=b'Active', max_length=255, null=True)),
                ('record_status_explanation', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on_fm', models.DateTimeField(help_text=b'Value of CreatedOn from the original FM database.', null=True)),
                ('created_by_fm', models.CharField(blank=True, help_text=b'Value of CreatedBy from the original FM database.', max_length=255, null=True)),
                ('modified_on_fm', models.DateTimeField(help_text=b'Value of ModifiedBy from the original FM database.', null=True, verbose_name=b'modified on (FM)')),
                ('modified_by_fm', models.CharField(blank=True, help_text=b'Value of ModifiedOn from the original FM database.', max_length=255, verbose_name=b'modified by (FM)')),
                ('dataset_literal', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.CharField(help_text=b'In the format {PRE}{ZEROS}{NN}, where PRE is a three-letter prefix indicating the record type (e.g. CBA for Authority), NN is an integer, and ZEROS is 0-9 zeros to pad NN such that ZEROS+NN is nine characters in length.', max_length=200, primary_key=True, serialize=False)),
                ('tracking_info', models.CharField(blank=True, max_length=255)),
                ('type_controlled', models.CharField(blank=True, choices=[(b'HS', b'HSTM Upload'), (b'PT', b'Printed'), (b'AU', b'Authorized'), (b'PD', b'Proofed'), (b'FU', b'Fully Entered'), (b'BD', b'Bulk Data Update')], db_index=True, max_length=2, null=True)),
                ('notes', models.TextField(blank=True)),
                ('authority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_records', to='isisdata.Authority')),
                ('belongs_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='isisdata.Dataset')),
                ('modified_by', models.ForeignKey(blank=True, help_text=b'The most recent user to modify this object.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('zotero_accession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zotero.ImportAccession')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricalAuthorityTracking',
            fields=[
                ('administrator_notes', models.TextField(blank=True, help_text=b'Curatorial discussion about the record.', null=True)),
                ('record_history', models.TextField(blank=True, help_text=b"Notes about the provenance of the information in this record. e.g. 'supplied by the author,' 'imported from SHOT bibliography,' 'generated by crawling UC Press website'", null=True)),
                ('modified_on', models.DateTimeField(blank=True, editable=False, help_text=b'Date and time at which this object was last updated.', null=True)),
                ('public', models.BooleanField(default=True, help_text=b'Controls whether this instance can be viewed by end users.')),
                ('record_status_value', models.CharField(blank=True, choices=[(b'Active', b'Active'), (b'Duplicate', b'Duplicate'), (b'Redirect', b'Redirect'), (b'Inactive', b'Inactive')], default=b'Active', max_length=255, null=True)),
                ('record_status_explanation', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on_fm', models.DateTimeField(help_text=b'Value of CreatedOn from the original FM database.', null=True)),
                ('created_by_fm', models.CharField(blank=True, help_text=b'Value of CreatedBy from the original FM database.', max_length=255, null=True)),
                ('modified_on_fm', models.DateTimeField(help_text=b'Value of ModifiedBy from the original FM database.', null=True, verbose_name=b'modified on (FM)')),
                ('modified_by_fm', models.CharField(blank=True, help_text=b'Value of ModifiedOn from the original FM database.', max_length=255, verbose_name=b'modified by (FM)')),
                ('dataset_literal', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.CharField(db_index=True, help_text=b'In the format {PRE}{ZEROS}{NN}, where PRE is a three-letter prefix indicating the record type (e.g. CBA for Authority), NN is an integer, and ZEROS is 0-9 zeros to pad NN such that ZEROS+NN is nine characters in length.', max_length=200)),
                ('tracking_info', models.CharField(blank=True, max_length=255)),
                ('type_controlled', models.CharField(blank=True, choices=[(b'HS', b'HSTM Upload'), (b'PT', b'Printed'), (b'AU', b'Authorized'), (b'PD', b'Proofed'), (b'FU', b'Fully Entered'), (b'BD', b'Bulk Data Update')], db_index=True, max_length=2, null=True)),
                ('notes', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('authority', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='isisdata.Authority')),
                ('belongs_to', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='isisdata.Dataset')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('zotero_accession', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='zotero.ImportAccession')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical authority tracking',
            },
        ),
    ]
