# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0063_auto_20170426_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='title_for_display',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='historicalcitation',
            name='title_for_display',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='authority',
            name='tracking_state',
            field=models.CharField(blank=True, choices=[(b'HS', b'HSTM Upload'), (b'PT', b'Printed'), (b'AU', b'Authorized'), (b'PD', b'Proofed'), (b'FU', b'Fully Entered'), (b'BD', b'Bulk Data Update'), (b'No', b'No')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='authoritytracking',
            name='type_controlled',
            field=models.CharField(blank=True, choices=[(b'HS', b'HSTM Upload'), (b'PT', b'Printed'), (b'AU', b'Authorized'), (b'PD', b'Proofed'), (b'FU', b'Fully Entered'), (b'BD', b'Bulk Data Update'), (b'NO', b'None')], db_index=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='citation',
            name='tracking_state',
            field=models.CharField(blank=True, choices=[(b'HS', b'HSTM Upload'), (b'PT', b'Printed'), (b'AU', b'Authorized'), (b'PD', b'Proofed'), (b'FU', b'Fully Entered'), (b'NO', b'None')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='historicalauthority',
            name='tracking_state',
            field=models.CharField(blank=True, choices=[(b'HS', b'HSTM Upload'), (b'PT', b'Printed'), (b'AU', b'Authorized'), (b'PD', b'Proofed'), (b'FU', b'Fully Entered'), (b'BD', b'Bulk Data Update'), (b'No', b'No')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='historicalauthoritytracking',
            name='type_controlled',
            field=models.CharField(blank=True, choices=[(b'HS', b'HSTM Upload'), (b'PT', b'Printed'), (b'AU', b'Authorized'), (b'PD', b'Proofed'), (b'FU', b'Fully Entered'), (b'BD', b'Bulk Data Update'), (b'NO', b'None')], db_index=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcitation',
            name='tracking_state',
            field=models.CharField(blank=True, choices=[(b'HS', b'HSTM Upload'), (b'PT', b'Printed'), (b'AU', b'Authorized'), (b'PD', b'Proofed'), (b'FU', b'Fully Entered'), (b'NO', b'None')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='historicallinkeddata',
            name='resource_name',
            field=models.CharField(blank=True, help_text=b'Title of the resource that the URN links to.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicallinkeddata',
            name='url',
            field=models.CharField(blank=True, help_text=b'If the URN is not an URL, you may optionally provide one here, for display purposes.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='tracking_state',
            field=models.CharField(blank=True, choices=[(b'HS', b'HSTM Upload'), (b'PT', b'Printed'), (b'AU', b'Authorized'), (b'PD', b'Proofed'), (b'FU', b'Fully Entered'), (b'BD', b'Bulk Data Update'), (b'No', b'No')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltracking',
            name='type_controlled',
            field=models.CharField(blank=True, choices=[(b'HS', b'HSTM Upload'), (b'PT', b'Printed'), (b'AU', b'Authorized'), (b'PD', b'Proofed'), (b'FU', b'Fully Entered'), (b'BD', b'Bulk Data Update'), (b'NO', b'None')], db_index=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='linkeddata',
            name='resource_name',
            field=models.CharField(blank=True, help_text=b'Title of the resource that the URN links to.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='linkeddata',
            name='type_controlled',
            field=models.ForeignKey(help_text=b'This field is used to determine what values are acceptable for the URN field, and to choose the correct display modality in the public-facing site and metadata', on_delete=django.db.models.deletion.CASCADE, to='isisdata.LinkedDataType', verbose_name=b'type'),
        ),
        migrations.AlterField(
            model_name='linkeddata',
            name='url',
            field=models.CharField(blank=True, help_text=b'If the URN is not an URL, you may optionally provide one here, for display purposes.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='type_controlled',
            field=models.CharField(blank=True, choices=[(b'HS', b'HSTM Upload'), (b'PT', b'Printed'), (b'AU', b'Authorized'), (b'PD', b'Proofed'), (b'FU', b'Fully Entered'), (b'BD', b'Bulk Data Update'), (b'NO', b'None')], db_index=True, max_length=2, null=True),
        ),
    ]
