# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 17:34
from __future__ import unicode_literals

from django.db import migrations, transaction


def set_citation_display_title(apps, schema_editor):
    from django.db.models import F
    Citation = apps.get_model("isisdata", "Citation")

    def get_display_title(obj):
        if not obj:
            return u'No linked citation'
        title = obj.title
        if not title:
            relation = obj.ccrelations.select_related('subject', 'object')\
                .filter(type_controlled__in=['RO', 'RB'])\
                .values('subject_id', 'subject__title', 'object__title')
            if relation.count() > 0:
                relation = relation.first()
            else:
                relation = None
            if relation:
                if relation['subject__title'] or relation['object__title']:
                    return u'Review: %s' % relation['subject__title'] if relation['subject_id'] != obj.id else relation['object__title']
                else:
                    return u'(no title)'
            return u'Untitled review'
        return title
            
    Citation.objects.filter(title__isnull=False).update(title_for_display=F('title'))
    while Citation.objects.filter(title_for_display__isnull=True).exists():
        print Citation.objects.filter(title_for_display__isnull=True).count()
        with transaction.atomic():
            for citation in Citation.objects.filter(title_for_display__isnull=True)[:1000]:
                citation.title_for_display = get_display_title(citation)
                citation.save()


def unset_citation_display_title(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0064_auto_20170508_1734'),
    ]

    operations = [
        migrations.RunPython(set_citation_display_title, unset_citation_display_title),
    ]
