# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-28 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0068_auto_20170728_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallinkeddata',
            name='url',
            field=models.TextField(blank=True, help_text=b'If the URN is not an URL, you may optionally provide one here, for display purposes.', null=True),
        ),
        migrations.AlterField(
            model_name='linkeddata',
            name='url',
            field=models.TextField(blank=True, help_text=b'If the URN is not an URL, you may optionally provide one here, for display purposes.', null=True),
        ),
    ]
