# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-30 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0069_auto_20170728_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallinkeddata',
            name='universal_resource_name',
            field=models.TextField(help_text=b'The value of the identifier (the actual DOI link or the value of the ISBN, etc). Will be a URN, URI, URL, or other unique identifier for a work, used as needed to provide information about how to find the digital object on the web or to identify the physical object uniquely.'),
        ),
        migrations.AlterField(
            model_name='linkeddata',
            name='universal_resource_name',
            field=models.TextField(help_text=b'The value of the identifier (the actual DOI link or the value of the ISBN, etc). Will be a URN, URI, URL, or other unique identifier for a work, used as needed to provide information about how to find the digital object on the web or to identify the physical object uniquely.'),
        ),
    ]
