# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-24 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0070_auto_20170730_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='asynctask',
            name='label',
            field=models.TextField(default=b''),
        ),
    ]
