# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-03 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0074_authorityvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorityvalue',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
