# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-01 19:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('isisdata', '0075_authorityvalue_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='aarelation',
            name='record_status_value',
            field=models.CharField(blank=True, choices=[(b'Active', b'Active'), (b'Duplicate', b'Delete'), (b'Redirect', b'Redirect'), (b'Inactive', b'Inactive')], default=b'Active', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='acrelation',
            name='record_status_value',
            field=models.CharField(blank=True, choices=[(b'Active', b'Active'), (b'Duplicate', b'Delete'), (b'Redirect', b'Redirect'), (b'Inactive', b'Inactive')], default=b'Active', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='record_status_value',
            field=models.CharField(blank=True, choices=[(b'Active', b'Active'), (b'Duplicate', b'Delete'), (b'Redirect', b'Redirect'), (b'Inactive', b'Inactive')], default=b'Active', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='authority',
            name='record_status_value',
            field=models.CharField(blank=True, choices=[(b'Active', b'Active'), (b'Duplicate', b'Delete'), (b'Redirect', b'Redirect'), (b'Inactive', b'Inactive')], default=b'Active', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='authoritytracking',
            name='record_status_value',
            field=models.CharField(blank=True, choices=[(b'Active', b'Active'), (b'Duplicate', b'Delete'), (b'Redirect', b'Redirect'), (b'Inactive', b'Inactive')], default=b'Active', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ccrelation',
            name='record_status_value',
            field=models.CharField(blank=True, choices=[(b'Active', b'Active'), (b'Duplicate', b'Delete'), (b'Redirect', b'Redirect'), (b'Inactive', b'Inactive')], default=b'Active', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='citation',
            name='record_status_value',
            field=models.CharField(blank=True, choices=[(b'Active', b'Active'), (b'Duplicate', b'Delete'), (b'Redirect', b'Redirect'), (b'Inactive', b'Inactive')], default=b'Active', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='record_status_value',
            field=models.CharField(blank=True, choices=[(b'Active', b'Active'), (b'Duplicate', b'Delete'), (b'Redirect', b'Redirect'), (b'Inactive', b'Inactive')], default=b'Active', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalacrelation',
            name='record_status_value',
            field=models.CharField(blank=True, choices=[(b'Active', b'Active'), (b'Duplicate', b'Delete'), (b'Redirect', b'Redirect'), (b'Inactive', b'Inactive')], default=b'Active', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalattribute',
            name='record_status_value',
            field=models.CharField(blank=True, choices=[(b'Active', b'Active'), (b'Duplicate', b'Delete'), (b'Redirect', b'Redirect'), (b'Inactive', b'Inactive')], default=b'Active', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalauthority',
            name='record_status_value',
            field=models.CharField(blank=True, choices=[(b'Active', b'Active'), (b'Duplicate', b'Delete'), (b'Redirect', b'Redirect'), (b'Inactive', b'Inactive')], default=b'Active', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalauthoritytracking',
            name='record_status_value',
            field=models.CharField(blank=True, choices=[(b'Active', b'Active'), (b'Duplicate', b'Delete'), (b'Redirect', b'Redirect'), (b'Inactive', b'Inactive')], default=b'Active', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalccrelation',
            name='record_status_value',
            field=models.CharField(blank=True, choices=[(b'Active', b'Active'), (b'Duplicate', b'Delete'), (b'Redirect', b'Redirect'), (b'Inactive', b'Inactive')], default=b'Active', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcitation',
            name='record_status_value',
            field=models.CharField(blank=True, choices=[(b'Active', b'Active'), (b'Duplicate', b'Delete'), (b'Redirect', b'Redirect'), (b'Inactive', b'Inactive')], default=b'Active', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicallinkeddata',
            name='record_status_value',
            field=models.CharField(blank=True, choices=[(b'Active', b'Active'), (b'Duplicate', b'Delete'), (b'Redirect', b'Redirect'), (b'Inactive', b'Inactive')], default=b'Active', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='record_status_value',
            field=models.CharField(blank=True, choices=[(b'Active', b'Active'), (b'Duplicate', b'Delete'), (b'Redirect', b'Redirect'), (b'Inactive', b'Inactive')], default=b'Active', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltracking',
            name='record_status_value',
            field=models.CharField(blank=True, choices=[(b'Active', b'Active'), (b'Duplicate', b'Delete'), (b'Redirect', b'Redirect'), (b'Inactive', b'Inactive')], default=b'Active', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='linkeddata',
            name='record_status_value',
            field=models.CharField(blank=True, choices=[(b'Active', b'Active'), (b'Duplicate', b'Delete'), (b'Redirect', b'Redirect'), (b'Inactive', b'Inactive')], default=b'Active', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='record_status_value',
            field=models.CharField(blank=True, choices=[(b'Active', b'Active'), (b'Duplicate', b'Delete'), (b'Redirect', b'Redirect'), (b'Inactive', b'Inactive')], default=b'Active', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='authoritycollection',
            name='authorities',
            field=models.ManyToManyField(related_name='in_collections', to='isisdata.Authority'),
        ),
        migrations.AddField(
            model_name='authoritycollection',
            name='createdBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authority_collections', to=settings.AUTH_USER_MODEL),
        ),
    ]
