# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-07 05:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0076_auto_20180604_2303'),
        ('isisdata', '0076_auto_20180601_1948'),
    ]

    operations = [
    ]
