# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-23 02:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('isisdata', '0077_merge_20180607_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='created_by_native',
            field=models.ForeignKey(blank=True, help_text=b'The user who created this object.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcitation',
            name='created_by_native',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
