# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-27 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0080_auto_20180711_0455'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedTimeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('authority', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='isisdata.Authority')),
            ],
        ),
        migrations.CreateModel(
            name='CachedTimelineTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('authors', models.TextField()),
                ('citation_type', models.CharField(blank=True, choices=[(b'BO', b'Book'), (b'AR', b'Article'), (b'CH', b'Chapter'), (b'RE', b'Review'), (b'ES', b'Essay Review'), (b'TH', b'Thesis'), (b'EV', b'Event'), (b'PR', b'Presentation'), (b'IN', b'Interactive Resource'), (b'WE', b'Website'), (b'AP', b'Application')], max_length=2, null=True, verbose_name=b'type')),
                ('citation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='isisdata.Citation')),
            ],
        ),
        migrations.CreateModel(
            name='CachedTimelineYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('book_count', models.BigIntegerField()),
                ('thesis_count', models.BigIntegerField()),
                ('chapter_count', models.BigIntegerField()),
                ('article_count', models.BigIntegerField()),
                ('review_count', models.BigIntegerField()),
                ('other_count', models.BigIntegerField()),
                ('timeline_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='isisdata.CachedTimeline')),
            ],
        ),
        migrations.AddField(
            model_name='cachedtimelinetitle',
            name='timeline_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='isisdata.CachedTimelineYear'),
        ),
    ]
