# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-24 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0081_auto_20190620_0206'),
        ('isisdata', '0082_auto_20190527_1804'),
    ]

    operations = [
    ]
