# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-02 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0084_cachedtimeline_recalculate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitationSubtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text=b'Name of the new subtype.', max_length=1000)),
                ('unique_name', models.CharField(db_index=True, help_text=b'Unique name of a subtype, use to reference a subtype.', max_length=1000)),
                ('description', models.TextField(blank=True, help_text=b"A brief description that will be displayed to help identify the authority. Such as, brief bio or a scope note. For classification terms will be text like 'Classification term from the XXX classification schema.'", null=True)),
                ('related_citation_type', models.CharField(blank=True, choices=[(b'BO', b'Book'), (b'AR', b'Article'), (b'CH', b'Chapter'), (b'RE', b'Review'), (b'ES', b'Essay Review'), (b'TH', b'Thesis'), (b'EV', b'Event'), (b'WO', b'Web Object'), (b'MO', b'Multimedia Object'), (b'AO', b'Archive Object'), (b'DR', b'Digital Resource'), (b'PC', b'Personal Recognition')], help_text=b'Type of which this object is a subtype, e.g. Review or Chapter.', max_length=2, null=True, verbose_name=b'citation type')),
            ],
        ),
        migrations.AlterField(
            model_name='acrelation',
            name='type_controlled',
            field=models.CharField(blank=True, choices=[(b'AU', b'Author'), (b'ED', b'Editor'), (b'AD', b'Advisor'), (b'CO', b'Contributor'), (b'TR', b'Translator'), (b'SU', b'Subject'), (b'CA', b'Category'), (b'PU', b'Publisher'), (b'SC', b'School'), (b'IN', b'Institution'), (b'ME', b'Meeting'), (b'PE', b'Periodical'), (b'BS', b'Book Series'), (b'CM', b'Committee Member'), (b'OR', b'Organizer'), (b'IV', b'Interviewer'), (b'GU', b'Guest'), (b'CR', b'Creator'), (b'PR', b'Producer'), (b'DI', b'Director'), (b'WR', b'Writer'), (b'PF', b'Performer'), (b'CL', b'Collector'), (b'AR', b'Archivist'), (b'RE', b'Researcher'), (b'DE', b'Developer'), (b'CP', b'Compiler'), (b'AW', b'Awardee'), (b'OF', b'Officer'), (b'HO', b'Host'), (b'DS', b'Distributor'), (b'AC', b'Archival Repository'), (b'MI', b'Maintaining Institution'), (b'PG', b'Presenting Group')], help_text=b'Used to specify the nature of the relationship between authority (as the subject) and the citation (as the object).', max_length=2, null=True, verbose_name=b'relationship type'),
        ),
        migrations.AlterField(
            model_name='cachedtimelinetitle',
            name='citation_type',
            field=models.CharField(blank=True, choices=[(b'BO', b'Book'), (b'AR', b'Article'), (b'CH', b'Chapter'), (b'RE', b'Review'), (b'ES', b'Essay Review'), (b'TH', b'Thesis'), (b'EV', b'Event'), (b'WO', b'Web Object'), (b'MO', b'Multimedia Object'), (b'AO', b'Archive Object'), (b'DR', b'Digital Resource'), (b'PC', b'Personal Recognition')], max_length=2, null=True, verbose_name=b'type'),
        ),
        migrations.AlterField(
            model_name='ccrelation',
            name='type_controlled',
            field=models.CharField(blank=True, choices=[(b'IC', b'Includes Chapter'), (b'ISA', b'Includes Series Article'), (b'ICO', b'Includes Citation Object'), (b'RO', b'Is Review Of'), (b'RE', b'Responds To'), (b'AS', b'Is Associated With'), (b'RB', b'Is Reviewed By')], help_text=b'Type of relationship between two citation records.', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='citation',
            name='type_controlled',
            field=models.CharField(blank=True, choices=[(b'BO', b'Book'), (b'AR', b'Article'), (b'CH', b'Chapter'), (b'RE', b'Review'), (b'ES', b'Essay Review'), (b'TH', b'Thesis'), (b'EV', b'Event'), (b'WO', b'Web Object'), (b'MO', b'Multimedia Object'), (b'AO', b'Archive Object'), (b'DR', b'Digital Resource'), (b'PC', b'Personal Recognition')], help_text=b'This list can be extended to the resource types specified by Doublin Core Recource Types http://dublincore.org/documents/resource-typelist/', max_length=2, null=True, verbose_name=b'type'),
        ),
        migrations.AlterField(
            model_name='historicalacrelation',
            name='type_controlled',
            field=models.CharField(blank=True, choices=[(b'AU', b'Author'), (b'ED', b'Editor'), (b'AD', b'Advisor'), (b'CO', b'Contributor'), (b'TR', b'Translator'), (b'SU', b'Subject'), (b'CA', b'Category'), (b'PU', b'Publisher'), (b'SC', b'School'), (b'IN', b'Institution'), (b'ME', b'Meeting'), (b'PE', b'Periodical'), (b'BS', b'Book Series'), (b'CM', b'Committee Member'), (b'OR', b'Organizer'), (b'IV', b'Interviewer'), (b'GU', b'Guest'), (b'CR', b'Creator'), (b'PR', b'Producer'), (b'DI', b'Director'), (b'WR', b'Writer'), (b'PF', b'Performer'), (b'CL', b'Collector'), (b'AR', b'Archivist'), (b'RE', b'Researcher'), (b'DE', b'Developer'), (b'CP', b'Compiler'), (b'AW', b'Awardee'), (b'OF', b'Officer'), (b'HO', b'Host'), (b'DS', b'Distributor'), (b'AC', b'Archival Repository'), (b'MI', b'Maintaining Institution'), (b'PG', b'Presenting Group')], help_text=b'Used to specify the nature of the relationship between authority (as the subject) and the citation (as the object).', max_length=2, null=True, verbose_name=b'relationship type'),
        ),
        migrations.AlterField(
            model_name='historicalccrelation',
            name='type_controlled',
            field=models.CharField(blank=True, choices=[(b'IC', b'Includes Chapter'), (b'ISA', b'Includes Series Article'), (b'ICO', b'Includes Citation Object'), (b'RO', b'Is Review Of'), (b'RE', b'Responds To'), (b'AS', b'Is Associated With'), (b'RB', b'Is Reviewed By')], help_text=b'Type of relationship between two citation records.', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcitation',
            name='type_controlled',
            field=models.CharField(blank=True, choices=[(b'BO', b'Book'), (b'AR', b'Article'), (b'CH', b'Chapter'), (b'RE', b'Review'), (b'ES', b'Essay Review'), (b'TH', b'Thesis'), (b'EV', b'Event'), (b'WO', b'Web Object'), (b'MO', b'Multimedia Object'), (b'AO', b'Archive Object'), (b'DR', b'Digital Resource'), (b'PC', b'Personal Recognition')], help_text=b'This list can be extended to the resource types specified by Doublin Core Recource Types http://dublincore.org/documents/resource-typelist/', max_length=2, null=True, verbose_name=b'type'),
        ),
        migrations.AddField(
            model_name='citation',
            name='subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='isisdata.CitationSubtype'),
        ),
        migrations.AddField(
            model_name='historicalcitation',
            name='subtype',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='isisdata.CitationSubtype'),
        ),
    ]
