# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-12 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0085_auto_20190902_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aarelation',
            name='record_status_value',
            field=models.CharField(blank=True, choices=[(b'Active', b'Active'), (b'Duplicate', b'Delete'), (b'Redirect', b'Redirect'), (b'Inactive', b'Inactive')], db_index=True, default=b'Active', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='acrelation',
            name='record_status_value',
            field=models.CharField(blank=True, choices=[(b'Active', b'Active'), (b'Duplicate', b'Delete'), (b'Redirect', b'Redirect'), (b'Inactive', b'Inactive')], db_index=True, default=b'Active', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='record_status_value',
            field=models.CharField(blank=True, choices=[(b'Active', b'Active'), (b'Duplicate', b'Delete'), (b'Redirect', b'Redirect'), (b'Inactive', b'Inactive')], db_index=True, default=b'Active', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='authority',
            name='record_status_value',
            field=models.CharField(blank=True, choices=[(b'Active', b'Active'), (b'Duplicate', b'Delete'), (b'Redirect', b'Redirect'), (b'Inactive', b'Inactive')], db_index=True, default=b'Active', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='authoritytracking',
            name='record_status_value',
            field=models.CharField(blank=True, choices=[(b'Active', b'Active'), (b'Duplicate', b'Delete'), (b'Redirect', b'Redirect'), (b'Inactive', b'Inactive')], db_index=True, default=b'Active', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ccrelation',
            name='record_status_value',
            field=models.CharField(blank=True, choices=[(b'Active', b'Active'), (b'Duplicate', b'Delete'), (b'Redirect', b'Redirect'), (b'Inactive', b'Inactive')], db_index=True, default=b'Active', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ccrelation',
            name='type_controlled',
            field=models.CharField(blank=True, choices=[(b'IC', b'Includes Chapter'), (b'ISA', b'Includes Series Article'), (b'ICO', b'Includes'), (b'RO', b'Is Review Of'), (b'RE', b'Responds To'), (b'AS', b'Is Associated With'), (b'RB', b'Is Reviewed By')], help_text=b'Type of relationship between two citation records.', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='citation',
            name='record_status_value',
            field=models.CharField(blank=True, choices=[(b'Active', b'Active'), (b'Duplicate', b'Delete'), (b'Redirect', b'Redirect'), (b'Inactive', b'Inactive')], db_index=True, default=b'Active', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='record_status_value',
            field=models.CharField(blank=True, choices=[(b'Active', b'Active'), (b'Duplicate', b'Delete'), (b'Redirect', b'Redirect'), (b'Inactive', b'Inactive')], db_index=True, default=b'Active', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalacrelation',
            name='record_status_value',
            field=models.CharField(blank=True, choices=[(b'Active', b'Active'), (b'Duplicate', b'Delete'), (b'Redirect', b'Redirect'), (b'Inactive', b'Inactive')], db_index=True, default=b'Active', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalattribute',
            name='record_status_value',
            field=models.CharField(blank=True, choices=[(b'Active', b'Active'), (b'Duplicate', b'Delete'), (b'Redirect', b'Redirect'), (b'Inactive', b'Inactive')], db_index=True, default=b'Active', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalauthority',
            name='record_status_value',
            field=models.CharField(blank=True, choices=[(b'Active', b'Active'), (b'Duplicate', b'Delete'), (b'Redirect', b'Redirect'), (b'Inactive', b'Inactive')], db_index=True, default=b'Active', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalauthoritytracking',
            name='record_status_value',
            field=models.CharField(blank=True, choices=[(b'Active', b'Active'), (b'Duplicate', b'Delete'), (b'Redirect', b'Redirect'), (b'Inactive', b'Inactive')], db_index=True, default=b'Active', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalccrelation',
            name='record_status_value',
            field=models.CharField(blank=True, choices=[(b'Active', b'Active'), (b'Duplicate', b'Delete'), (b'Redirect', b'Redirect'), (b'Inactive', b'Inactive')], db_index=True, default=b'Active', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalccrelation',
            name='type_controlled',
            field=models.CharField(blank=True, choices=[(b'IC', b'Includes Chapter'), (b'ISA', b'Includes Series Article'), (b'ICO', b'Includes'), (b'RO', b'Is Review Of'), (b'RE', b'Responds To'), (b'AS', b'Is Associated With'), (b'RB', b'Is Reviewed By')], help_text=b'Type of relationship between two citation records.', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcitation',
            name='record_status_value',
            field=models.CharField(blank=True, choices=[(b'Active', b'Active'), (b'Duplicate', b'Delete'), (b'Redirect', b'Redirect'), (b'Inactive', b'Inactive')], db_index=True, default=b'Active', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicallinkeddata',
            name='record_status_value',
            field=models.CharField(blank=True, choices=[(b'Active', b'Active'), (b'Duplicate', b'Delete'), (b'Redirect', b'Redirect'), (b'Inactive', b'Inactive')], db_index=True, default=b'Active', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='record_status_value',
            field=models.CharField(blank=True, choices=[(b'Active', b'Active'), (b'Duplicate', b'Delete'), (b'Redirect', b'Redirect'), (b'Inactive', b'Inactive')], db_index=True, default=b'Active', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltracking',
            name='record_status_value',
            field=models.CharField(blank=True, choices=[(b'Active', b'Active'), (b'Duplicate', b'Delete'), (b'Redirect', b'Redirect'), (b'Inactive', b'Inactive')], db_index=True, default=b'Active', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='linkeddata',
            name='record_status_value',
            field=models.CharField(blank=True, choices=[(b'Active', b'Active'), (b'Duplicate', b'Delete'), (b'Redirect', b'Redirect'), (b'Inactive', b'Inactive')], db_index=True, default=b'Active', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='record_status_value',
            field=models.CharField(blank=True, choices=[(b'Active', b'Active'), (b'Duplicate', b'Delete'), (b'Redirect', b'Redirect'), (b'Inactive', b'Inactive')], db_index=True, default=b'Active', max_length=255, null=True),
        ),
    ]
