# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-01 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0088_auto_20200126_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='is_hstm_uploaded',
            field=models.CharField(blank=True, choices=[(b'HS', b'HSTM Upload')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='historicalcitation',
            name='is_hstm_uploaded',
            field=models.CharField(blank=True, choices=[(b'HS', b'HSTM Upload')], max_length=2, null=True),
        ),
    ]
