# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-01 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0089_auto_20200201_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citation',
            old_name='is_hstm_uploaded',
            new_name='hstm_uploaded',
        ),
        migrations.RenameField(
            model_name='historicalcitation',
            old_name='is_hstm_uploaded',
            new_name='hstm_uploaded',
        ),
    ]
