# Generated by Django 3.0.7 on 2021-06-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0091_auto_20200601_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='complete_citation',
            field=models.TextField(blank=True, help_text='A complete citation that can be used to show a record if detailed information has not been entered yet.', null=True),
        ),
        migrations.AddField(
            model_name='citation',
            name='stub_record_status',
            field=models.CharField(blank=True, choices=[('SR', 'Stub Record'), ('RR', 'Regular Record')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='historicalcitation',
            name='complete_citation',
            field=models.TextField(blank=True, help_text='A complete citation that can be used to show a record if detailed information has not been entered yet.', null=True),
        ),
        migrations.AddField(
            model_name='historicalcitation',
            name='stub_record_status',
            field=models.CharField(blank=True, choices=[('SR', 'Stub Record'), ('RR', 'Regular Record')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='aarelation',
            name='type_controlled',
            field=models.CharField(blank=True, choices=[('IDTO', 'Is Identical To'), ('PAOF', 'Is Parent Of'), ('ASWI', 'Is Associated With')], help_text='Controlled term specifying the nature of the relationship (the predicate between the subject and object).', max_length=5, null=True),
        ),
    ]
