# Generated by Django 3.0.7 on 2021-07-17 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0092_auto_20210424_1857'),
        ('isisdata', '0092_auto_20210627_2124'),
    ]

    operations = [
    ]
