# Generated by Django 3.0.7 on 2021-08-26 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('isisdata', '0094_auto_20210717_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributetype',
            name='value_content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('model', 'textvalue'), ('model', 'charvalue'), ('model', 'intvalue'), ('model', 'datetimevalue'), ('model', 'datevalue'), ('model', 'floatvalue'), ('model', 'locationvalue'), ('model', 'isodatevalue'), ('model', 'isodaterangevalue'), ('model', 'authorityvalue'), ('model', 'citationvalue'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='attribute_value', to='contenttypes.ContentType'),
        ),
        migrations.CreateModel(
            name='CitationValue',
            fields=[
                ('value_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='isisdata.Value')),
                ('name', models.TextField(blank=True, null=True)),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isisdata.Citation')),
            ],
            options={
                'verbose_name': 'citation',
            },
            bases=('isisdata.value',),
        ),
    ]
