# Generated by Django 3.1.12 on 2022-01-07 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0095_auto_20210826_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleBooksData',
            fields=[
                ('citation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='isisdata.citation')),
                ('image_url', models.URLField(max_length=255)),
                ('image_size', models.CharField(blank=True, max_length=255)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
