# Generated by Django 3.1.12 on 2022-01-06 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0095_auto_20210826_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikipediaData',
            fields=[
                ('authority', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='isisdata.authority')),
                ('img_url', models.URLField(max_length=255)),
                ('intro', models.TextField(blank=True, null=True)),
                ('credit', models.URLField(max_length=255)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
