# Generated by Django 3.1.13 on 2022-06-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0096_featuredauthority_googlebooksdata_wikipediadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
