# Generated by Django 3.1.12 on 2022-01-26 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0096_wikipediadata'),
        ('isisdata', '0097_auto_20220107_1746'),
    ]

    operations = [
    ]
