# Generated by Django 3.1.12 on 2022-08-30 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0098_tenantrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='tenants',
            field=models.ManyToManyField(to='isisdata.Tenant'),
        ),
    ]
