# Generated by Django 3.1.12 on 2022-01-30 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0098_merge_20220126_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedAuthority',
            fields=[
                ('authority', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='isisdata.authority')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
    ]
