# Generated by Django 3.1.13 on 2022-08-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0098_citationcollection_coverimage_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citationcollection',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='isisdata.Authority'),
        ),
    ]
