# Generated by Django 3.1.13 on 2023-07-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0099_auto_20220812_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='isisdata.Authority'),
        ),
    ]
