# Generated by Django 3.1.13 on 2022-05-06 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0096_featuredauthority_googlebooksdata_wikipediadata'),
        ('isisdata', '0099_featuredauthority'),
    ]

    operations = [
    ]
