# Generated by Django 3.1.12 on 2022-09-09 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0099_authority_tenants'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='identifier',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
