# Generated by Django 3.1.12 on 2022-10-20 02:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('isisdata', '0100_tenant_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantrule',
            name='allowed_action',
            field=models.CharField(choices=[('view', 'View'), ('update', 'Update')], default='update', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tenant',
            name='users',
            field=models.ManyToManyField(related_name='tenants', to=settings.AUTH_USER_MODEL),
        ),
    ]
