# Generated by Django 3.1.12 on 2022-11-11 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0101_auto_20221020_0245'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navigation_color', models.CharField(blank=True, max_length=255, null=True)),
                ('link_color', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tenantrule',
            name='allowed_action',
            field=models.CharField(choices=[('view', 'Editor'), ('update', 'Administrator')], max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='settings',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to='isisdata.tenantsettings'),
        ),
    ]
