# Generated by Django 3.1.13 on 2022-11-20 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0102_auto_20221111_0211'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantPageBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_of_columns', models.IntegerField()),
                ('tenant_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_blocks', to='isisdata.tenantsettings')),
            ],
        ),
        migrations.CreateModel(
            name='TenantPageBlockColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_index', models.IntegerField()),
                ('content', models.TextField()),
                ('page_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_columns', to='isisdata.tenantpageblock')),
            ],
        ),
    ]
