# Generated by Django 3.1.13 on 2022-11-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0103_tenantpageblock_tenantpageblockcolumn'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantpageblock',
            name='block_index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
