# Generated by Django 3.1.13 on 2022-11-24 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0104_tenantpageblock_block_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantpageblock',
            options={'ordering': ['block_index']},
        ),
        migrations.AlterModelOptions(
            name='tenantpageblockcolumn',
            options={'ordering': ['column_index']},
        ),
        migrations.AddField(
            model_name='tenantpageblock',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
