# Generated by Django 3.1.13 on 2022-12-20 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0105_auto_20221124_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantpageblock',
            name='block_type',
            field=models.CharField(blank=True, choices=[('HM', 'Main home block'), ('HO', 'Main other blocks'), ('AB', 'About pagge blocks')], db_index=True, default='HO', max_length=255, null=True),
        ),
    ]
