# Generated by Django 3.1.13 on 2023-01-21 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0106_tenantpageblock_block_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='home_page_template',
            field=models.CharField(blank=True, help_text='If there is a customized template that should be used instead of the configurable page block, the path to the template needs to go here. Do not change this value unless you really know what your are doing. A developer of IsisCB Explore will need to create the template.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='use_home_page_template',
            field=models.BooleanField(default=False, help_text="Set this value to True if the template specified via 'home page template' should be used instead of the configurable page blocks. A template path needs to be specified for this to work. Do not change this value unless you know what you are doing."),
        ),
    ]
