# Generated by Django 3.0.7 on 2023-01-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0107_auto_20230121_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='contact_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_logos'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='authority_default_image',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_authorities'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='citations_external_links_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
