# Generated by Django 3.0.7 on 2023-01-27 03:05

from django.db import migrations, models
import django.db.models.deletion
import isisdata.models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0108_auto_20230121_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=isisdata.models.TenantImage.upload_path)),
                ('tenant_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='isisdata.TenantSettings')),
            ],
        ),
    ]
