# Generated by Django 3.0.7 on 2023-01-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0109_tenantimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantimage',
            name='image_type',
            field=models.CharField(blank=True, choices=[('HM', 'Main home image'), ('HO', 'Main other image'), ('AB', 'About page image')], db_index=True, default='HO', max_length=255, null=True),
        ),
    ]
