# Generated by Django 3.0.7 on 2023-01-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0110_tenantimage_image_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantimage',
            name='image_index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tenantpageblock',
            name='block_type',
            field=models.CharField(blank=True, choices=[('HM', 'Main home block'), ('HO', 'Main other blocks'), ('AB', 'About page blocks')], db_index=True, default='HO', max_length=255, null=True),
        ),
    ]
