# Generated by Django 3.0.7 on 2023-01-31 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0111_auto_20230128_2142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantimage',
            options={'ordering': ['image_index']},
        ),
        migrations.AddField(
            model_name='tenantimage',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenantimage',
            name='link_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
