# Generated by Django 3.0.7 on 2023-02-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0112_auto_20230131_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantsettings',
            name='authority_default_image',
        ),
        migrations.AlterField(
            model_name='tenantimage',
            name='image_type',
            field=models.CharField(blank=True, choices=[('AI', 'Authority Default Image'), ('AB', 'About page image')], db_index=True, default='AB', max_length=255, null=True),
        ),
    ]
