# Generated by Django 3.0.7 on 2023-02-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0113_auto_20230205_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='google_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='twitter_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tenantimage',
            name='image_type',
            field=models.CharField(blank=True, choices=[('DAU', 'Authority Default Image Author'), ('DPE', 'Authority Default Image Person'), ('DCO', 'Authority Default Image Concept'), ('DIN', 'Authority Default Image Institution'), ('DGE', 'Authority Default Image Geographic Term'), ('DPU', 'Authority Default Image Publisher'), ('DTI', 'Authority Default Image Timeperiod'), ('DCL', 'Authority Default Image Classification Term'), ('AB', 'About page image')], db_index=True, default='AB', max_length=255, null=True),
        ),
    ]
