# Generated by Django 3.1.13 on 2023-02-24 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0115_tenantsettings_twitter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='owning_tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_authorities', to='isisdata.tenant'),
        ),
        migrations.AddField(
            model_name='citation',
            name='owning_tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_citations', to='isisdata.tenant'),
        ),
        migrations.AddField(
            model_name='historicalauthority',
            name='owning_tenant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='isisdata.tenant'),
        ),
        migrations.AddField(
            model_name='historicalcitation',
            name='owning_tenant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='isisdata.tenant'),
        ),
        migrations.AddField(
            model_name='historicalperson',
            name='owning_tenant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='isisdata.tenant'),
        ),
    ]
