# Generated by Django 3.1.13 on 2023-03-29 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0117_auto_20230314_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='belongs_to_tenant',
            new_name='owning_tenant',
        ),
    ]
