# Generated by Django 3.1.13 on 2023-04-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0118_auto_20230329_0155'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_system', models.CharField(blank=True, choices=[('SPWT', 'Weldon Thesaurus Terms (2002-present)'), ('SPWC', 'Weldon Classification System (2002-present)'), ('GUE', 'Guerlac Committee Classification System (1953-2001)'), ('NEU', 'Neu'), ('MW', 'Whitrow Classification System (1913-1999)'), ('SHOT', 'SHOT Thesaurus Terms'), ('FHSA', 'Forum for the History of Science in America'), ('SAC', 'Search App Concept'), ('PN', 'Proper name'), ('NEW', 'Tenant Classification System')], db_index=True, default='SPWC', help_text='This field is for legacy purposes only. For systems migrated from the previous version of IsisCB when a simple database field was used for classification systems. All new classification systems should be set to "NEW".', max_length=4, null=True)),
                ('name', models.CharField(db_index=True, help_text='Name of the classification system.', max_length=1000)),
                ('description', models.CharField(db_index=True, help_text='Description of the classification system.', max_length=1000)),
            ],
        ),
    ]
