# Generated by Django 3.1.13 on 2023-04-23 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0119_classificationsystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='classification_system_object',
            field=models.ForeignKey(blank=True, help_text='Specifies the classification system that is the source of the authority. Used to group resources by the Classification system. The system used currently is the Weldon System. All the other ones are for reference or archival purposes only.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='isisdata.classificationsystem'),
        ),
        migrations.AddField(
            model_name='historicalauthority',
            name='classification_system_object',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Specifies the classification system that is the source of the authority. Used to group resources by the Classification system. The system used currently is the Weldon System. All the other ones are for reference or archival purposes only.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='isisdata.classificationsystem'),
        ),
        migrations.AddField(
            model_name='historicalperson',
            name='classification_system_object',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Specifies the classification system that is the source of the authority. Used to group resources by the Classification system. The system used currently is the Weldon System. All the other ones are for reference or archival purposes only.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='isisdata.classificationsystem'),
        ),
        migrations.AlterField(
            model_name='authority',
            name='classification_system',
            field=models.CharField(blank=True, choices=[('SPWT', 'Weldon Thesaurus Terms (2002-present)'), ('SPWC', 'Weldon Classification System (2002-present)'), ('GUE', 'Guerlac Committee Classification System (1953-2001)'), ('NEU', 'Neu'), ('MW', 'Whitrow Classification System (1913-1999)'), ('SHOT', 'SHOT Thesaurus Terms'), ('FHSA', 'Forum for the History of Science in America'), ('SAC', 'Search App Concept'), ('PN', 'Proper name')], db_index=True, default='SPWC', help_text='DEPRECATED! Use classification_system_object instead! Specifies the classification system that is the source of the authority. Used to group resources by the Classification system. The system used currently is the Weldon System. All the other ones are for reference or archival purposes only.', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='classificationsystem',
            name='classification_system',
            field=models.CharField(blank=True, choices=[('SPWT', 'Weldon Thesaurus Terms (2002-present)'), ('SPWC', 'Weldon Classification System (2002-present)'), ('GUE', 'Guerlac Committee Classification System (1953-2001)'), ('NEU', 'Neu'), ('MW', 'Whitrow Classification System (1913-1999)'), ('SHOT', 'SHOT Thesaurus Terms'), ('FHSA', 'Forum for the History of Science in America'), ('SAC', 'Search App Concept'), ('PN', 'Proper name'), ('NEW', 'Tenant Classification System')], db_index=True, default='SPWC', help_text='This field is for legacy purposes only. For systems migrated from the previous version of IsisCB when a simple database field was used for classification systems. All new classification systems should be set to "Tenant Classification System".', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='historicalauthority',
            name='classification_system',
            field=models.CharField(blank=True, choices=[('SPWT', 'Weldon Thesaurus Terms (2002-present)'), ('SPWC', 'Weldon Classification System (2002-present)'), ('GUE', 'Guerlac Committee Classification System (1953-2001)'), ('NEU', 'Neu'), ('MW', 'Whitrow Classification System (1913-1999)'), ('SHOT', 'SHOT Thesaurus Terms'), ('FHSA', 'Forum for the History of Science in America'), ('SAC', 'Search App Concept'), ('PN', 'Proper name')], db_index=True, default='SPWC', help_text='DEPRECATED! Use classification_system_object instead! Specifies the classification system that is the source of the authority. Used to group resources by the Classification system. The system used currently is the Weldon System. All the other ones are for reference or archival purposes only.', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='classification_system',
            field=models.CharField(blank=True, choices=[('SPWT', 'Weldon Thesaurus Terms (2002-present)'), ('SPWC', 'Weldon Classification System (2002-present)'), ('GUE', 'Guerlac Committee Classification System (1953-2001)'), ('NEU', 'Neu'), ('MW', 'Whitrow Classification System (1913-1999)'), ('SHOT', 'SHOT Thesaurus Terms'), ('FHSA', 'Forum for the History of Science in America'), ('SAC', 'Search App Concept'), ('PN', 'Proper name')], db_index=True, default='SPWC', help_text='DEPRECATED! Use classification_system_object instead! Specifies the classification system that is the source of the authority. Used to group resources by the Classification system. The system used currently is the Weldon System. All the other ones are for reference or archival purposes only.', max_length=4, null=True),
        ),
    ]
