# Generated by Django 3.1.13 on 2023-04-30 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0120_auto_20230423_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationsystem',
            name='owning_tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_classification_systems', to='isisdata.tenant'),
        ),
    ]
