# Generated by Django 3.1.13 on 2023-04-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0121_classificationsystem_owning_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationsystem',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Marks a classification system as the default for authorities of types classification term, concept, cross reference, bibliographic list, and time period.'),
        ),
        migrations.AddField(
            model_name='classificationsystem',
            name='subject_search_searchable',
            field=models.BooleanField(default=True, help_text='Marks a classification system as being included in the subject search.'),
        ),
    ]
