# Generated by Django 3.1.13 on 2023-06-11 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0124_auto_20230605_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='default_featured_authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='isisdata.authority'),
        ),
        migrations.AddField(
            model_name='tenantsettings',
            name='default_featured_citation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='isisdata.citation'),
        ),
    ]
