# Generated by Django 3.1.13 on 2023-10-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0126_tenantsettings_subject_searches_all_tenants'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='public_search_all_tenants_default',
            field=models.BooleanField(default=False),
        ),
    ]
