# Generated by Django 3.1.13 on 2023-11-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0128_cachedtimeline_owning_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='owning_tenant_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='tenant_portal',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
