# Generated by Django 3.1.13 on 2023-11-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0129_auto_20231107_0221'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='\n                             Title of notification (cannot be longer than 255 characters)', max_length=255, null=True)),
                ('text', models.TextField(default='', help_text='Notification message')),
                ('created_on', models.DateTimeField()),
                ('modified_on', models.DateTimeField(null=True)),
            ],
        ),
    ]
