# Generated by Django 3.1.13 on 2023-11-17 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0130_systemnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemnotification',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
