# Generated by Django 3.1.13 on 2023-11-18 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0131_systemnotification_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemnotification',
            name='level',
            field=models.CharField(choices=[('INFO', 'Info'), ('WARN', 'Warning'), ('DANG', 'Danger')], default='INFO', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='systemnotification',
            name='active',
            field=models.BooleanField(default=False, help_text='Indicates if message should be shown.'),
        ),
    ]
