# Generated by Django 3.1.13 on 2024-01-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0133_tenant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='hide_title_in_navbar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('ACT', 'Active'), ('INA', 'Inactive')], db_index=True, default='ACT', help_text='\n             Mark a tenant as active to include it in the searches of other tenants when \n             "all projects" are searched, and in the seachbar on the user profile pages.\n             ', max_length=4),
        ),
    ]
