# Generated by Django 3.1.13 on 2024-02-09 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0134_auto_20240114_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='blog_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
