# Generated by Django 3.1.13 on 2024-09-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0138_dataset_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetrule',
            name='can_write',
            field=models.BooleanField(default=False),
        ),
    ]
