# Generated by Django 3.1.13 on 2024-11-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0139_datasetrule_can_write'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attribute',
            index=models.Index(fields=['source_instance_id'], name='isisdata_at_source__5d629e_idx'),
        ),
    ]
