# Generated by Django 3.1.13 on 2024-11-27 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0139_datasetrule_can_write'),
        ('isisdata', '0140_auto_20241120_0304'),
    ]

    operations = [
    ]
