# Generated by Django 4.2.20 on 2025-03-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0141_merge_20241127_0232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalacrelation',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical authority-citation relationship', 'verbose_name_plural': 'historical authority-citation relationships'},
        ),
        migrations.AlterModelOptions(
            name='historicalattribute',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical attribute', 'verbose_name_plural': 'historical attributes'},
        ),
        migrations.AlterModelOptions(
            name='historicalauthority',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical authority record', 'verbose_name_plural': 'historical authority records'},
        ),
        migrations.AlterModelOptions(
            name='historicalauthoritytracking',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical authority tracking', 'verbose_name_plural': 'historical authority trackings'},
        ),
        migrations.AlterModelOptions(
            name='historicalccrelation',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical citation-citation relationship', 'verbose_name_plural': 'historical citation-citation relationships'},
        ),
        migrations.AlterModelOptions(
            name='historicalcitation',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical citation', 'verbose_name_plural': 'historical citations'},
        ),
        migrations.AlterModelOptions(
            name='historicallinkeddata',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical linked data entry', 'verbose_name_plural': 'historical linked data entries'},
        ),
        migrations.AlterModelOptions(
            name='historicalperson',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical person', 'verbose_name_plural': 'historical persons'},
        ),
        migrations.AlterModelOptions(
            name='historicaltracking',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical tracking', 'verbose_name_plural': 'historical trackings'},
        ),
        migrations.AlterField(
            model_name='crudrule',
            name='crud_action',
            field=models.CharField(choices=[('view', 'View'), ('update', 'Update'), ('delete', 'Delete')], max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalacrelation',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalattribute',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalauthority',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalauthoritytracking',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalccrelation',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcitation',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicallinkeddata',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltracking',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
