# Generated by Django 5.2 on 2026-02-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0142_alter_historicalacrelation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='raw_search',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
