# Generated by Django 5.2 on 2026-04-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0143_searchquery_raw_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='asynctask',
            name='task_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
