version: 0.0
os: linux
files:
  - source: isiscb
    destination: /home/ec2-user/isiscb/isiscb
  - source: isiscb/deploy/supervisor.conf
    destination: /etc/supervisor/conf.d/supervisor.conf

hooks:
  BeforeInstall:
    - location: /home/ec2-user/isiscb/isiscb/awsdeploy/BeforeInstall.sh
      timeout: 1000
  ApplicationStart:
    - location: /home/ec2-user/isiscb/isiscb/awsdeploy/ApplicationStart.sh
      timeout: 1000
