# Generated by Django 5.2 on 2026-03-15 21:33

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('isisdata', '0143_searchquery_raw_search'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedPartDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.CharField(blank=True, max_length=255, null=True)),
                ('volume_free_text', models.CharField(blank=True, max_length=255, null=True)),
                ('volume_begin', models.IntegerField(blank=True, null=True)),
                ('volume_end', models.IntegerField(blank=True, null=True)),
                ('issue_free_text', models.CharField(blank=True, max_length=255, null=True)),
                ('issue_begin', models.IntegerField(blank=True, null=True)),
                ('issue_end', models.IntegerField(blank=True, null=True)),
                ('pages_free_text', models.CharField(blank=True, max_length=255, null=True)),
                ('page_begin', models.IntegerField(blank=True, null=True)),
                ('page_end', models.IntegerField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('extent', models.PositiveIntegerField(blank=True, null=True)),
                ('extent_note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportedAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(db_index=True, max_length=1000)),
                ('description', models.TextField(blank=True, null=True)),
                ('type_controlled', models.CharField(blank=True, choices=[('PE', 'Person'), ('IN', 'Institution'), ('TI', 'Time Period'), ('GE', 'Geographic Term'), ('SE', 'Serial Publication'), ('CT', 'Category Division'), ('CO', 'Concept'), ('CW', 'Creative Work'), ('EV', 'Event'), ('CR', 'Cross-reference'), ('BL', 'Bibliographic List')], db_index=True, max_length=2, null=True, verbose_name='type')),
                ('classification_system', models.CharField(blank=True, choices=[('SPWT', 'Weldon Thesaurus Terms (2002-present)'), ('SPWC', 'Weldon Classification System (2002-present)'), ('GUE', 'Guerlac Committee Classification System (1953-2001)'), ('NEU', 'Neu'), ('MW', 'Whitrow Classification System (1913-1999)'), ('SHOT', 'SHOT Thesaurus Terms'), ('FHSA', 'Forum for the History of Science in America'), ('SAC', 'Search App Concept'), ('PN', 'Proper name')], db_index=True, default='SPWC', max_length=4, null=True)),
                ('classification_code', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('classification_hierarchy', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('record_status', models.CharField(blank=True, choices=[('AC', 'Active'), ('DU', 'Duplicate'), ('RD', 'Redirect'), ('IN', 'Inactive')], max_length=2, null=True)),
                ('personal_name_last', models.CharField(blank=True, max_length=255)),
                ('personal_name_first', models.CharField(blank=True, max_length=255)),
                ('personal_name_suffix', models.CharField(blank=True, max_length=255)),
                ('personal_name_preferred', models.CharField(blank=True, max_length=255)),
                ('classification_system_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='isisdata.classificationsystem')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('owning_tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_json_authorities', to='isisdata.tenant')),
                ('tenants', models.ManyToManyField(to='isisdata.tenant')),
            ],
            options={
                'verbose_name': 'authority record',
                'verbose_name_plural': 'authority records',
            },
        ),
        migrations.CreateModel(
            name='ImportedACRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type_controlled', models.CharField(blank=True, choices=[('AU', 'Author'), ('ED', 'Editor'), ('AD', 'Advisor'), ('CO', 'Contributor'), ('TR', 'Translator'), ('SU', 'Subject'), ('CA', 'Category'), ('PU', 'Publisher'), ('SC', 'School'), ('IN', 'Institution'), ('ME', 'Meeting'), ('PE', 'Periodical'), ('BS', 'Book Series'), ('CM', 'Committee Member'), ('OR', 'Organizer'), ('IV', 'Interviewer'), ('GU', 'Guest'), ('CR', 'Creator'), ('PR', 'Producer'), ('DI', 'Director'), ('WR', 'Writer'), ('PF', 'Performer'), ('CL', 'Collector'), ('AR', 'Archivist'), ('RE', 'Researcher'), ('DE', 'Developer'), ('CP', 'Compiler'), ('AW', 'Awardee'), ('OF', 'Officer'), ('HO', 'Host'), ('DS', 'Distributor'), ('AC', 'Archival Repository'), ('MI', 'Maintaining Institution'), ('PG', 'Presenting Group')], max_length=2, null=True, verbose_name='relationship type')),
                ('type_broad_controlled', models.CharField(blank=True, choices=[('PR', 'Has Personal Responsibility For'), ('SC', 'Provides Subject Content About'), ('IH', 'Is Institutional Host Of'), ('PH', 'Is Publication Host Of')], max_length=2, null=True, verbose_name='relationship type (broad)')),
                ('type_free', models.CharField(blank=True, max_length=255, verbose_name='relationship type (free-text)')),
                ('name_for_display_in_citation', models.CharField(blank=True, max_length=255, null=True)),
                ('name_as_entered', models.CharField(blank=True, max_length=255, null=True)),
                ('personal_name_first', models.CharField(blank=True, max_length=255, null=True)),
                ('personal_name_last', models.CharField(blank=True, max_length=255, null=True)),
                ('personal_name_suffix', models.CharField(blank=True, max_length=255, null=True)),
                ('data_display_order', models.FloatField(default=1.0)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('authority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jsonimport.importedauthority')),
            ],
            options={
                'verbose_name': 'authority-citation relationship',
                'verbose_name_plural': 'authority-citation relationships',
            },
        ),
        migrations.CreateModel(
            name='ImportedCCRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('type_controlled', models.CharField(blank=True, choices=[('AU', 'Author'), ('ED', 'Editor'), ('AD', 'Advisor'), ('CO', 'Contributor'), ('TR', 'Translator'), ('SU', 'Subject'), ('CA', 'Category'), ('PU', 'Publisher'), ('SC', 'School'), ('IN', 'Institution'), ('ME', 'Meeting'), ('PE', 'Periodical'), ('BS', 'Book Series'), ('CM', 'Committee Member'), ('OR', 'Organizer'), ('IV', 'Interviewer'), ('GU', 'Guest'), ('CR', 'Creator'), ('PR', 'Producer'), ('DI', 'Director'), ('WR', 'Writer'), ('PF', 'Performer'), ('CL', 'Collector'), ('AR', 'Archivist'), ('RE', 'Researcher'), ('DE', 'Developer'), ('CP', 'Compiler'), ('AW', 'Awardee'), ('OF', 'Officer'), ('HO', 'Host'), ('DS', 'Distributor'), ('AC', 'Archival Repository'), ('MI', 'Maintaining Institution'), ('PG', 'Presenting Group')], max_length=3, null=True)),
                ('type_free', models.CharField(blank=True, max_length=255)),
                ('data_display_order', models.FloatField(default=1.0)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'citation-citation relationship',
                'verbose_name_plural': 'citation-citation relationships',
            },
        ),
        migrations.CreateModel(
            name='ImportedCitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_on', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=2000)),
                ('additional_titles', models.TextField(blank=True, help_text='Additional titles (not delimited, free text).', null=True)),
                ('book_series', models.CharField(blank=True, help_text='Used for books, and potentially other works in a series.', max_length=255, null=True)),
                ('created_native', models.DateTimeField(blank=True, null=True)),
                ('complete_citation', models.TextField(blank=True, help_text='A complete citation that can be used to show a record if detailed information has not been entered yet.', null=True)),
                ('stub_record_status', models.CharField(blank=True, choices=[('SR', 'Stub Record'), ('RR', 'Regular Record')], max_length=3, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type_controlled', models.CharField(blank=True, choices=[('BO', 'Book'), ('AR', 'Article'), ('CH', 'Chapter'), ('RE', 'Review'), ('ES', 'Essay Review'), ('TH', 'Thesis'), ('EV', 'Event'), ('WO', 'Web Object'), ('MO', 'Multimedia Object'), ('AO', 'Archive Object'), ('DR', 'Digital Resource'), ('PC', 'Personal Recognition')], max_length=2, null=True, verbose_name='type')),
                ('abstract', models.TextField(blank=True, null=True)),
                ('edition_details', models.TextField(blank=True, null=True)),
                ('physical_details', models.CharField(blank=True, max_length=255, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('language', models.ManyToManyField(blank=True, null=True, to='isisdata.language')),
                ('owning_tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_imported_citations', to='isisdata.tenant')),
                ('related_authorities', models.ManyToManyField(related_name='authorities_related', through='jsonimport.ImportedACRelation', to='jsonimport.importedauthority')),
                ('related_citations', models.ManyToManyField(related_name='citations_related', through='jsonimport.ImportedCCRelation', to='jsonimport.importedcitation')),
                ('subtype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='isisdata.citationsubtype')),
                ('tenants', models.ManyToManyField(to='isisdata.tenant')),
                ('part_details', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jsonimport.importedpartdetails')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='importedccrelation',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relations_to', to='jsonimport.importedcitation'),
        ),
        migrations.AddField(
            model_name='importedccrelation',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relations_from', to='jsonimport.importedcitation'),
        ),
        migrations.CreateModel(
            name='ImportedAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('value_int', models.IntegerField(default=0)),
                ('value_float', models.FloatField()),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_char', models.CharField(max_length=2000)),
                ('value_date_time', models.DateTimeField()),
                ('value_date_range_start', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), size=2)),
                ('source_instance_id', models.CharField(max_length=200)),
                ('type_controlled', models.CharField(blank=True, choices=[('Integer', 'INT'), ('String', 'STRING'), ('Char', 'CHAR'), ('Datetime', 'DATETIME'), ('Float', 'FLOAT'), ('Citation', 'CITATION'), ('Authority', 'AUTHORITY')], db_index=True, max_length=255, null=True)),
                ('source_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('value_authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonimport.importedauthority')),
                ('value_citation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonimport.importedcitation')),
            ],
        ),
        migrations.AddField(
            model_name='importedacrelation',
            name='citation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jsonimport.importedcitation'),
        ),
        migrations.CreateModel(
            name='ImportedLinkedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('universal_resource_name', models.TextField(db_index=True, help_text='The value of the identifier (the actual DOI link or the value of the ISBN, etc). Will be a URN, URI, URL, or other unique identifier for a work, used as needed to provide information about how to find the digital object on the web or to identify the physical object uniquely.')),
                ('resource_name', models.CharField(blank=True, help_text='Title of the resource that the URN links to.', max_length=255, null=True)),
                ('url', models.TextField(blank=True, help_text='If the URN is not an URL, you may optionally provide one here, for display purposes.', null=True)),
                ('subject_instance_id', models.CharField(max_length=200)),
                ('type_controlled_broad', models.CharField(blank=True, max_length=255)),
                ('type_free', models.CharField(blank=True, max_length=255)),
                ('access_status', models.CharField(blank=True, max_length=255, null=True)),
                ('access_status_date_verified', models.DateField(blank=True, null=True)),
                ('subject_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('type_controlled', models.ForeignKey(help_text='This field is used to determine what values are acceptable for the URN field, and to choose the correct display modality in the public-facing site and metadata', null=True, on_delete=django.db.models.deletion.SET_NULL, to='isisdata.linkeddatatype', verbose_name='type')),
            ],
        ),
    ]
