# Generated by Django 5.2 on 2026-03-28 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0143_searchquery_raw_search'),
        ('jsonimport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importedattribute',
            name='source_content_type',
        ),
        migrations.RemoveField(
            model_name='importedattribute',
            name='source_instance_id',
        ),
        migrations.RemoveField(
            model_name='importedattribute',
            name='type_controlled',
        ),
        migrations.RemoveField(
            model_name='importedattribute',
            name='value_char',
        ),
        migrations.RemoveField(
            model_name='importedattribute',
            name='value_date_range_start',
        ),
        migrations.RemoveField(
            model_name='importedattribute',
            name='value_date_time',
        ),
        migrations.RemoveField(
            model_name='importedattribute',
            name='value_float',
        ),
        migrations.RemoveField(
            model_name='importedattribute',
            name='value_int',
        ),
        migrations.RemoveField(
            model_name='importedattribute',
            name='value_text',
        ),
        migrations.AddField(
            model_name='importedattribute',
            name='attribute_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='isisdata.attributetype'),
        ),
        migrations.AddField(
            model_name='importedattribute',
            name='value',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ImportedDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('dataset_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('dataset_creator', models.CharField(blank=True, max_length=255, null=True)),
                ('dataset_date', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='importedauthority',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jsonimport.importeddataset'),
        ),
        migrations.AddField(
            model_name='importedcitation',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jsonimport.importeddataset'),
        ),
    ]
