# Generated by Django 5.2 on 2026-04-05 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0143_searchquery_raw_search'),
        ('jsonimport', '0002_remove_importedattribute_source_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importedauthority',
            name='owning_tenant',
        ),
        migrations.RemoveField(
            model_name='importedauthority',
            name='tenants',
        ),
        migrations.RemoveField(
            model_name='importedcitation',
            name='owning_tenant',
        ),
        migrations.RemoveField(
            model_name='importedcitation',
            name='tenants',
        ),
        migrations.AddField(
            model_name='importedacrelation',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jsonimport.importeddataset'),
        ),
        migrations.AddField(
            model_name='importedacrelation',
            name='local_dataset_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importedauthority',
            name='local_dataset_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importedccrelation',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jsonimport.importeddataset'),
        ),
        migrations.AddField(
            model_name='importedccrelation',
            name='local_dataset_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importedcitation',
            name='local_dataset_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importeddataset',
            name='owning_tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='isisdata.tenant'),
        ),
    ]
