# Generated by Django 5.2 on 2026-04-05 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0143_searchquery_raw_search'),
        ('jsonimport', '0003_remove_importedauthority_owning_tenant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importedauthority',
            name='classification_system',
        ),
        migrations.AddField(
            model_name='importedacrelation',
            name='existing_authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='isisdata.authority'),
        ),
    ]
