# Generated by Django 5.2 on 2026-04-05 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0144_asynctask_task_type'),
        ('jsonimport', '0004_remove_importedauthority_classification_system_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importeddataset',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='isisdata.asynctask'),
        ),
    ]
