# Generated by Django 5.2 on 2026-04-12 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0144_asynctask_task_type'),
        ('jsonimport', '0005_importeddataset_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedccrelation',
            name='existing_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_relations_to', to='isisdata.citation'),
        ),
        migrations.AddField(
            model_name='importedccrelation',
            name='existing_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_relations_from', to='isisdata.citation'),
        ),
        migrations.AlterField(
            model_name='importedccrelation',
            name='type_controlled',
            field=models.CharField(blank=True, choices=[('IC', 'Includes Chapter'), ('ISA', 'Includes Series Article'), ('ICO', 'Includes'), ('RO', 'Is Review Of'), ('RE', 'Responds To'), ('AS', 'Is Associated With'), ('RB', 'Is Reviewed By')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='importedcitation',
            name='related_authorities',
            field=models.ManyToManyField(related_name='citations_related', through='jsonimport.ImportedACRelation', to='jsonimport.importedauthority'),
        ),
    ]
