# Generated by Django 5.2 on 2026-04-12 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonimport', '0006_importedccrelation_existing_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedRecordStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('ERROR', 'Error')], max_length=10)),
                ('message', models.TextField(blank=True, null=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jsonimport.importeddataset')),
            ],
        ),
        migrations.CreateModel(
            name='ImportedACRelationStatus',
            fields=[
                ('importedrecordstatus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jsonimport.importedrecordstatus')),
                ('acrelation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonimport.importedacrelation')),
            ],
            bases=('jsonimport.importedrecordstatus',),
        ),
        migrations.CreateModel(
            name='ImportedAuthorityStatus',
            fields=[
                ('importedrecordstatus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jsonimport.importedrecordstatus')),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonimport.importedauthority')),
            ],
            bases=('jsonimport.importedrecordstatus',),
        ),
        migrations.CreateModel(
            name='ImportedCCRelationStatus',
            fields=[
                ('importedrecordstatus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jsonimport.importedrecordstatus')),
                ('ccrelation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonimport.importedccrelation')),
            ],
            bases=('jsonimport.importedrecordstatus',),
        ),
        migrations.CreateModel(
            name='ImportedCitationStatus',
            fields=[
                ('importedrecordstatus_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jsonimport.importedrecordstatus')),
                ('citation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsonimport.importedcitation')),
            ],
            bases=('jsonimport.importedrecordstatus',),
        ),
    ]
