# Generated by Django 5.2 on 2026-04-12 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonimport', '0007_importedrecordstatus_importedacrelationstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedacrelationstatus',
            name='acrelation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jsonimport.importedacrelation'),
        ),
        migrations.AlterField(
            model_name='importedauthoritystatus',
            name='authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jsonimport.importedauthority'),
        ),
        migrations.AlterField(
            model_name='importedccrelationstatus',
            name='ccrelation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jsonimport.importedccrelation'),
        ),
        migrations.AlterField(
            model_name='importedcitationstatus',
            name='citation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jsonimport.importedcitation'),
        ),
    ]
