# Generated by Django 5.2 on 2026-05-01 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonimport', '0008_alter_importedacrelationstatus_acrelation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importeddataset',
            name='authorities_imported_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importeddataset',
            name='citations_imported_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importeddataset',
            name='dataset_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
