# Generated by Django 5.2 on 2026-05-03 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonimport', '0009_importeddataset_authorities_imported_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importedcitation',
            name='part_details',
        ),
        migrations.AddField(
            model_name='importedpartdetails',
            name='citation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='part_details', to='jsonimport.importedcitation'),
        ),
        migrations.AlterField(
            model_name='importedacrelation',
            name='authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jsonimport.importedauthority'),
        ),
        migrations.AlterField(
            model_name='importedccrelation',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relations_from', to='jsonimport.importedcitation'),
        ),
    ]
