# Generated by Django 5.2 on 2026-05-03 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonimport', '0010_remove_importedcitation_part_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedattribute',
            name='value_citation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jsonimport.importedcitation'),
        ),
    ]
