# Generated by Django 5.2 on 2026-06-07 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonimport', '0011_alter_importedattribute_value_citation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importedcitation',
            name='publication_date',
        ),
        migrations.AlterField(
            model_name='importedattribute',
            name='value_authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jsonimport.importedauthority'),
        ),
    ]
