# Generated by Django 5.2 on 2026-06-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonimport', '0014_importeddataset_dataset_import_errors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importeddataset',
            name='authority_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importeddataset',
            name='citation_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importeddataset',
            name='s3_authority_file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importeddataset',
            name='s3_citation_file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
