# Generated by Django 5.2 on 2026-08-04 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isisdata', '0145_aarelation_json_import_dataset_and_more'),
        ('jsonimport', '0017_importeddataset_s3_processing_results_file_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedacrelation',
            name='belongs_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='isisdata.dataset'),
        ),
        migrations.AddField(
            model_name='importedauthority',
            name='belongs_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='isisdata.dataset'),
        ),
        migrations.AddField(
            model_name='importedccrelation',
            name='belongs_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='isisdata.dataset'),
        ),
        migrations.AddField(
            model_name='importedcitation',
            name='belongs_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='isisdata.dataset'),
        ),
    ]
