# Generated by Django 3.0.5 on 2020-06-01 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openurl', '0002_auto_20160323_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resolver',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resolver',
            name='endpoint',
            field=models.URLField(help_text='The address to which CoINS metadata will be appended to create an OpenURL link.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='resolver',
            name='link_icon',
            field=models.URLField(blank=True, help_text='Location of an image that will be rendered as a link next to search results.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='resolver',
            name='link_text',
            field=models.CharField(blank=True, help_text='Text that will be rendered as a link next to search results if ``link_icon`` is not available.', max_length=1000, null=True),
        ),
    ]
