# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zotero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftcitation',
            name='issue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='draftcitation',
            name='page_end',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='draftcitation',
            name='page_start',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='draftcitation',
            name='volume',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
