# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zotero', '0002_auto_20160216_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instanceresolutionevent',
            name='to_instance_id',
            field=models.CharField(max_length=1000),
        ),
    ]
