# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zotero', '0004_auto_20160322_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftacrelation',
            name='type_broad_controlled',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='draftacrelation',
            name='type_controlled',
            field=models.CharField(blank=True, choices=[('AU', 'Author'), ('ED', 'Editor'), ('AD', 'Advisor'), ('CO', 'Contributor'), ('TR', 'Translator'), ('SU', 'Subject'), ('CA', 'Category'), ('PU', 'Publisher'), ('SC', 'School'), ('IN', 'Institution'), ('ME', 'Meeting'), ('PE', 'Periodical'), ('BS', 'Book Series')], max_length=2, null=True),
        ),
    ]
