# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-28 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zotero', '0020_draftcitation_extent_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftcitation',
            name='physical_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
