# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-28 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zotero', '0021_draftcitation_physical_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftcitationlinkeddata',
            name='value',
            field=models.TextField(),
        ),
    ]
