# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-09 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zotero', '0023_draftacrelation_data_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftcitation',
            name='issue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
