# Generated by Django 3.0.5 on 2020-06-01 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('isisdata', '0091_auto_20200601_0013'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zotero', '0025_importaccession_import_errors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftacrelation',
            name='authority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citation_relations', to='zotero.DraftAuthority'),
        ),
        migrations.AlterField(
            model_name='draftacrelation',
            name='citation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authority_relations', to='zotero.DraftCitation'),
        ),
        migrations.AlterField(
            model_name='draftacrelation',
            name='imported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='draftattribute',
            name='imported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='draftauthority',
            name='imported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='draftauthoritylinkeddata',
            name='imported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='draftccrelation',
            name='imported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='draftccrelation',
            name='object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relations_to', to='zotero.DraftCitation'),
        ),
        migrations.AlterField(
            model_name='draftccrelation',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relations_from', to='zotero.DraftCitation'),
        ),
        migrations.AlterField(
            model_name='draftcitation',
            name='imported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='draftcitation',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='isisdata.Language'),
        ),
        migrations.AlterField(
            model_name='draftcitationlinkeddata',
            name='imported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fieldresolutionevent',
            name='for_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fieldresolutions_for', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='importaccession',
            name='imported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='importaccession',
            name='ingest_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='isisdata.Dataset'),
        ),
        migrations.AlterField(
            model_name='instanceresolutionevent',
            name='for_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instanceresolutions_for', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='instanceresolutionevent',
            name='to_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instanceresolutions_to', to='contenttypes.ContentType'),
        ),
    ]
