# Generated by Django 3.1.13 on 2023-03-29 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zotero', '0027_importaccession_tenant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importaccession',
            old_name='tenant',
            new_name='owning_tenant',
        ),
    ]
