# Generated by Django 3.1.13 on 2023-06-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zotero', '0028_auto_20230329_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftauthority',
            name='type_controlled',
            field=models.CharField(blank=True, choices=[('PE', 'Person'), ('IN', 'Institution'), ('TI', 'Time Period'), ('GE', 'Geographic Term'), ('SE', 'Serial Publication'), ('CT', 'Category Division'), ('CO', 'Concept'), ('CW', 'Creative Work'), ('EV', 'Event'), ('CR', 'Cross-reference')], max_length=2, null=True),
        ),
    ]
