branch-defaults:
  master:
    environment: production
  develop:
    environment: isiscb-develop
global:
  #application_name: IsisCB Staging Python 3
  #application_name: IsisCB Stagin Python 3.12
  application_name: isiscb-staging-python312
  #application_name: IsisCB Celery Staging Python 3 (non worker)
  #application_name: isiscb-production-p3
  #application_name: isiscb-production-celery-p3
  default_ec2_keyname: isiscb-eb
  default_platform: Python 3.12 running on 64bit Amazon Linux 2023/4.5.1
  default_region: us-west-2
  #profile: eb-cli
  sc: git
